/**
 * Articulation Engine — per-note performance articulations.
 * Supports legato, staccato, accent, glide/portamento, vibrato, and more.
 */

export type ArticulationType =
  | 'normal'
  | 'legato'
  | 'staccato'
  | 'staccatissimo'
  | 'accent'
  | 'marcato'
  | 'tenuto'
  | 'glide'
  | 'portamento'
  | 'vibrato'
  | 'tremolo'
  | 'trill'
  | 'bend'
  | 'slide-up'
  | 'slide-down'
  | 'palm-mute'
  | 'harmonic';

export interface ArticulationConfig {
  type: ArticulationType;
  /** Intensity/depth 0-1 */
  intensity: number;
  /** Rate in Hz (for vibrato, tremolo, trill) */
  rate?: number;
  /** Duration modifier (fraction of original, 0.1-2.0) */
  durationScale?: number;
  /** Velocity modifier (added, -64 to 64) */
  velocityOffset?: number;
  /** Glide/portamento time in ms */
  glideTimeMs?: number;
  /** Pitch bend range in semitones (for bends) */
  bendSemitones?: number;
  /** Trill interval in semitones */
  trillInterval?: number;
}

export interface ArticulatedNote {
  pitch: number;
  velocity: number;
  /** Start time in seconds */
  startTime: number;
  /** Duration in seconds */
  duration: number;
  /** Applied articulation */
  articulation: ArticulationType;
  /** Pitch envelope events (time, pitch pairs relative to start) */
  pitchEnvelope?: Array<{ time: number; pitch: number }>;
  /** Velocity envelope (time, velocity pairs for dynamics) */
  velocityEnvelope?: Array<{ time: number; velocity: number }>;
  /** CC automation generated by articulation */
  ccAutomation?: Array<{ time: number; cc: number; value: number }>;
}

export interface NoteInput {
  pitch: number;
  velocity: number;
  startTime: number;
  duration: number;
}

/** Default articulation presets */
export const ARTICULATION_PRESETS: Record<ArticulationType, ArticulationConfig> = {
  normal: { type: 'normal', intensity: 0 },
  legato: { type: 'legato', intensity: 0.8, durationScale: 1.1, glideTimeMs: 50 },
  staccato: { type: 'staccato', intensity: 0.7, durationScale: 0.3, velocityOffset: 10 },
  staccatissimo: { type: 'staccatissimo', intensity: 0.9, durationScale: 0.15, velocityOffset: 15 },
  accent: { type: 'accent', intensity: 0.6, velocityOffset: 30 },
  marcato: { type: 'marcato', intensity: 0.8, velocityOffset: 40, durationScale: 0.8 },
  tenuto: { type: 'tenuto', intensity: 0.5, durationScale: 1.0, velocityOffset: 5 },
  glide: { type: 'glide', intensity: 0.7, glideTimeMs: 150 },
  portamento: { type: 'portamento', intensity: 0.6, glideTimeMs: 300 },
  vibrato: { type: 'vibrato', intensity: 0.5, rate: 5.5 },
  tremolo: { type: 'tremolo', intensity: 0.6, rate: 8 },
  trill: { type: 'trill', intensity: 0.7, rate: 12, trillInterval: 2 },
  bend: { type: 'bend', intensity: 0.5, bendSemitones: 2 },
  'slide-up': { type: 'slide-up', intensity: 0.6, bendSemitones: 12, glideTimeMs: 200 },
  'slide-down': { type: 'slide-down', intensity: 0.6, bendSemitones: 12, glideTimeMs: 200 },
  'palm-mute': { type: 'palm-mute', intensity: 0.8, durationScale: 0.4, velocityOffset: -15 },
  harmonic: { type: 'harmonic', intensity: 0.7, velocityOffset: -20 },
};

/** Apply articulation to a single note */
export function applyArticulation(note: NoteInput, config: ArticulationConfig): ArticulatedNote {
  const result: ArticulatedNote = {
    pitch: note.pitch,
    velocity: note.velocity,
    startTime: note.startTime,
    duration: note.duration,
    articulation: config.type,
  };

  // Duration scaling
  if (config.durationScale != null) {
    result.duration = note.duration * config.durationScale;
  }

  // Velocity offset
  if (config.velocityOffset != null) {
    result.velocity = Math.max(1, Math.min(127, note.velocity + config.velocityOffset));
  }

  // Type-specific processing
  switch (config.type) {
    case 'vibrato':
      result.pitchEnvelope = generateVibrato(note, config);
      break;
    case 'tremolo':
      result.velocityEnvelope = generateTremolo(note, config);
      break;
    case 'trill':
      result.pitchEnvelope = generateTrill(note, config);
      break;
    case 'bend':
      result.pitchEnvelope = generateBend(note, config);
      break;
    case 'slide-up':
      result.pitchEnvelope = generateSlide(note, config, 'up');
      break;
    case 'slide-down':
      result.pitchEnvelope = generateSlide(note, config, 'down');
      break;
    case 'palm-mute':
      // CC for mute brightness
      result.ccAutomation = [
        { time: note.startTime, cc: 74, value: Math.round(30 * config.intensity) },
        { time: note.startTime + result.duration, cc: 74, value: 80 },
      ];
      break;
    case 'harmonic':
      // Pitch up an octave in "harmonic" style (flageolet)
      result.ccAutomation = [
        { time: note.startTime, cc: 74, value: 127 }, // brightness up
        { time: note.startTime + result.duration, cc: 74, value: 80 },
      ];
      break;
    default:
      break;
  }

  return result;
}

/** Generate vibrato pitch envelope */
function generateVibrato(note: NoteInput, config: ArticulationConfig): Array<{ time: number; pitch: number }> {
  const rate = config.rate ?? 5.5;
  const depth = config.intensity * 0.5; // max ±0.5 semitones
  const points: Array<{ time: number; pitch: number }> = [];
  const steps = Math.ceil(note.duration * rate * 4); // 4 points per cycle

  for (let i = 0; i <= steps; i++) {
    const t = (i / steps) * note.duration;
    // Gradual onset (fade in vibrato over first 20% of note)
    const onset = Math.min(1, t / (note.duration * 0.2));
    const offset = Math.sin(2 * Math.PI * rate * t) * depth * onset;
    points.push({ time: note.startTime + t, pitch: note.pitch + offset });
  }

  return points;
}

/** Generate tremolo velocity envelope */
function generateTremolo(note: NoteInput, config: ArticulationConfig): Array<{ time: number; velocity: number }> {
  const rate = config.rate ?? 8;
  const depth = config.intensity;
  const points: Array<{ time: number; velocity: number }> = [];
  const steps = Math.ceil(note.duration * rate * 4);

  for (let i = 0; i <= steps; i++) {
    const t = (i / steps) * note.duration;
    const modulation = (1 + Math.sin(2 * Math.PI * rate * t)) / 2;
    const velocity = Math.round(note.velocity * (1 - depth * modulation));
    points.push({ time: note.startTime + t, velocity: Math.max(1, velocity) });
  }

  return points;
}

/** Generate trill pitch envelope (alternating between note and note+interval) */
function generateTrill(note: NoteInput, config: ArticulationConfig): Array<{ time: number; pitch: number }> {
  const rate = config.rate ?? 12;
  const interval = config.trillInterval ?? 2;
  const points: Array<{ time: number; pitch: number }> = [];
  const steps = Math.ceil(note.duration * rate);

  for (let i = 0; i <= steps; i++) {
    const t = (i / steps) * note.duration;
    const isUpper = i % 2 === 1;
    points.push({
      time: note.startTime + t,
      pitch: note.pitch + (isUpper ? interval : 0),
    });
  }

  return points;
}

/** Generate pitch bend envelope */
function generateBend(note: NoteInput, config: ArticulationConfig): Array<{ time: number; pitch: number }> {
  const semitones = (config.bendSemitones ?? 2) * config.intensity;
  const bendDuration = Math.min(note.duration * 0.3, 0.2); // bend in first 30% or 200ms

  return [
    { time: note.startTime, pitch: note.pitch },
    { time: note.startTime + bendDuration * 0.5, pitch: note.pitch + semitones },
    { time: note.startTime + bendDuration, pitch: note.pitch },
    { time: note.startTime + note.duration, pitch: note.pitch },
  ];
}

/** Generate slide pitch envelope */
function generateSlide(
  note: NoteInput,
  config: ArticulationConfig,
  direction: 'up' | 'down',
): Array<{ time: number; pitch: number }> {
  const semitones = (config.bendSemitones ?? 12) * config.intensity;
  const slideTime = (config.glideTimeMs ?? 200) / 1000;

  if (direction === 'up') {
    return [
      { time: note.startTime, pitch: note.pitch - semitones },
      { time: note.startTime + slideTime, pitch: note.pitch },
      { time: note.startTime + note.duration, pitch: note.pitch },
    ];
  } else {
    return [
      { time: note.startTime, pitch: note.pitch },
      { time: note.startTime + note.duration - slideTime, pitch: note.pitch },
      { time: note.startTime + note.duration, pitch: note.pitch - semitones },
    ];
  }
}

/** Apply legato between consecutive notes (overlap + glide) */
export function applyLegatoChain(
  notes: NoteInput[],
  config: ArticulationConfig,
): ArticulatedNote[] {
  if (notes.length === 0) return [];

  const sorted = [...notes].sort((a, b) => a.startTime - b.startTime);
  const glideTime = (config.glideTimeMs ?? 50) / 1000;
  const result: ArticulatedNote[] = [];

  for (let i = 0; i < sorted.length; i++) {
    const note = sorted[i];
    const next = sorted[i + 1];
    const articulated = applyArticulation(note, config);

    // Extend note to overlap with next note for legato transition
    if (next && config.type === 'legato') {
      const gap = next.startTime - (note.startTime + note.duration);
      if (gap > -0.1) {
        // Add overlap
        articulated.duration = next.startTime - note.startTime + glideTime;
        // Add pitch glide to next note
        articulated.pitchEnvelope = [
          { time: note.startTime, pitch: note.pitch },
          { time: next.startTime, pitch: note.pitch },
          { time: next.startTime + glideTime, pitch: next.pitch },
        ];
      }
    }

    result.push(articulated);
  }

  return result;
}

/** Apply articulation to array of notes */
export function applyArticulationToAll(
  notes: NoteInput[],
  config: ArticulationConfig,
): ArticulatedNote[] {
  if (config.type === 'legato' || config.type === 'portamento' || config.type === 'glide') {
    return applyLegatoChain(notes, config);
  }
  return notes.map((n) => applyArticulation(n, config));
}

/** Get all available articulation types with labels */
export function getArticulationTypes(): Array<{ type: ArticulationType; label: string; description: string }> {
  return [
    { type: 'normal', label: 'Normal', description: 'No articulation' },
    { type: 'legato', label: 'Legato', description: 'Smooth connected notes with glide' },
    { type: 'staccato', label: 'Staccato', description: 'Short detached notes' },
    { type: 'staccatissimo', label: 'Staccatissimo', description: 'Very short notes' },
    { type: 'accent', label: 'Accent', description: 'Emphasized attack' },
    { type: 'marcato', label: 'Marcato', description: 'Strong accent with shortened duration' },
    { type: 'tenuto', label: 'Tenuto', description: 'Held for full duration' },
    { type: 'glide', label: 'Glide', description: 'Pitch slide between notes' },
    { type: 'portamento', label: 'Portamento', description: 'Slow pitch slide between notes' },
    { type: 'vibrato', label: 'Vibrato', description: 'Pitch modulation' },
    { type: 'tremolo', label: 'Tremolo', description: 'Volume modulation' },
    { type: 'trill', label: 'Trill', description: 'Rapid alternation with upper note' },
    { type: 'bend', label: 'Bend', description: 'Quick pitch bend up and back' },
    { type: 'slide-up', label: 'Slide Up', description: 'Slide into note from below' },
    { type: 'slide-down', label: 'Slide Down', description: 'Slide out of note downward' },
    { type: 'palm-mute', label: 'Palm Mute', description: 'Dampened tone' },
    { type: 'harmonic', label: 'Harmonic', description: 'Flageolet / natural harmonic' },
  ];
}
