import type { MiniGameMeta } from './types'

/** Registry of all available couch mini-games. */
export const MINI_GAMES: MiniGameMeta[] = [
  {
    id: 'flatworld-survival-shooter',
    title: 'Flatworld Survival Shooter',
    description: 'Terraria-like 2.5D survival — mine, craft, build & fight! Procedural world, day/night cycle, bosses. Deathmatch, co-op & survival modes.',
    minPlayers: 1,
    maxPlayers: 8,
    icon: '⛏️',
  },
  {
    id: 'empire-rts',
    title: 'Empire RTS',
    description: 'Kingdom Two Crowns-style side-scrolling RTS — build your base, recruit units, manage economy & defend against enemy waves. Co-op, PvP, Skirmish & Endless modes.',
    minPlayers: 1,
    maxPlayers: 8,
    icon: '🏰',
  },
  {
    id: 'honest-living',
    title: 'Honest Living',
    description: 'Open-world farming RPG — farm, mine, fish, craft, build machines, automate, trade, build relationships, explore biomes & complete quests!',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🌾',
  },
  {
    id: 'bunny-arena',
    title: 'Bunny Arena',
    description: 'Physics-based ragdoll platformer — jump, grab, kick and fight! Arena, puzzle & free play modes.',
    minPlayers: 1,
    maxPlayers: 8,
    icon: '🐰',
  },
  {
    id: 'war-is-on-rts',
    title: 'War Is On RTS',
    description: 'Top-down RTS — command units, build warrens, gather food, destroy enemy bases! Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🐀',
  },
  {
    id: 'danger-zone-area-control',
    title: 'Danger Zone',
    description: 'Real-time area control — deploy armies, conquer territories, earn coins/gems/stars! VS conquest & co-op defend.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏰',
  },
  {
    id: 'underpaid-timemanagement',
    title: 'Underpaid',
    description: 'Cooperative cooking chaos — chop, cook, assemble & serve orders before time runs out! Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🍳',
  },
  {
    id: 'magic-decks-tcg',
    title: 'Magic Decks TCG',
    description: 'Real-time card battler — play creatures, spells & enchantments, auto-attack lanes, earn coins/gems/stars!',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🃏',
  },
  {
    id: 'menace-shooter',
    title: 'Menace',
    description: 'Top-down open-world action — steal cars, complete missions, evade police! Free-roam, VS rampage & co-op heist. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🚗',
  },
  {
    id: 'atomic-postapo',
    title: 'Atomic Postapo',
    description: 'Isometric action RPG — explore the wasteland, fight mutants & raiders, loot ruins! Co-op survival & VS deathmatch. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '☢️',
  },
  {
    id: 'warzone-fpp',
    title: 'Warzone FPP',
    description: 'Large-scale 2D combat — capture points, vehicles & ticket system! Conquest, TDM & co-op assault. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 8,
    icon: '🪖',
  },
  {
    id: 'game-of-castles',
    title: 'Game of Castles',
    description: 'HoMM3-inspired strategy — adventure map, town management, tactical combat! Skirmish, co-op & VS. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🐴',
  },
  {
    id: 'snakes',
    title: 'Snakes',
    description: 'Classic Snake — eat food, grow longer, avoid walls and other players!',
    minPlayers: 1,
    maxPlayers: 8,
    icon: '🐍',
  },
  {
    id: 'tron',
    title: 'Tron',
    description: 'Light Cycles — leave a trail and force opponents to crash!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🏍️',
  },
  {
    id: 'pong',
    title: 'Pong',
    description: 'Classic Pong — defend your side, 2-4 player arena!',
    minPlayers: 2,
    maxPlayers: 4,
    icon: '🏓',
  },
  {
    id: 'tag',
    title: 'Tag',
    description: 'One player is "it" — tag others to pass it on! Least time as "it" wins.',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🏃',
  },
  {
    id: 'painters',
    title: 'Painters',
    description: 'Paint the arena with your colour — most territory wins!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🎨',
  },
  {
    id: 'asteroids',
    title: 'Asteroids',
    description: 'Shoot asteroids in space! Rotate, thrust, and fire. Most points wins.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '☄️',
  },
  {
    id: 'reaction',
    title: 'Reaction',
    description: 'Test your reflexes — press your button when the screen turns green!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '⚡',
  },
  {
    id: 'sumo',
    title: 'Sumo',
    description: 'Push opponents off the shrinking arena! Last one standing wins.',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🤼',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    description: 'Co-op brick breaker — multiple paddles, one ball, smash all the bricks!',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🧱',
  },
  {
    id: 'dodgeball',
    title: 'Dodgeball',
    description: 'Dodge bouncing balls! Get hit = eliminated. Last alive wins.',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🏐',
  },
  {
    id: 'race',
    title: 'Race',
    description: 'Top-down oval race — first to complete 3 laps wins!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🏁',
  },
  {
    id: 'tanks',
    title: 'Tanks',
    description: 'Tank warfare — turrets, thrust, and ricocheting bullets!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🪖',
  },
  {
    id: 'maze',
    title: 'Maze',
    description: 'Race through a randomly generated maze to the exit!',
    minPlayers: 2,
    maxPlayers: 4,
    icon: '🏗️',
  },
  {
    id: 'hockey',
    title: 'Hockey',
    description: 'Air hockey — hit the puck into the opponent goal!',
    minPlayers: 2,
    maxPlayers: 4,
    icon: '🏒',
  },
  {
    id: 'volleyball',
    title: 'Volleyball',
    description: 'Side-view volleyball with gravity — hit the ball over the net!',
    minPlayers: 2,
    maxPlayers: 4,
    icon: '🏐',
  },
  {
    id: 'archery',
    title: 'Archery',
    description: 'Aim your crosshair at the moving target — highest score wins!',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏹',
  },
  {
    id: 'fishing',
    title: 'Fishing',
    description: 'Fish swim past — cast your hook at the right moment! Most fish wins.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🎣',
  },
  {
    id: 'lava',
    title: 'Lava',
    description: 'The floor is lava! Platforms decay — last one standing wins.',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🌋',
  },
  {
    id: 'joust',
    title: 'Joust',
    description: 'Flap to fly and bump opponents from above to eliminate them!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🐔',
  },
  {
    id: 'collect',
    title: 'Collect',
    description: 'Grab coins before others — most coins when time runs out wins!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🪙',
  },
  {
    id: 'bounce',
    title: 'Bounce',
    description: 'Multi-sided paddle game — miss the ball and lose a life!',
    minPlayers: 2,
    maxPlayers: 4,
    icon: '🏓',
  },
  {
    id: 'spiral',
    title: 'Spiral',
    description: 'Shrinking arena with a rotating bar — touch the wall and die!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🌀',
  },
  {
    id: 'duel',
    title: 'Duel',
    description: 'Wild west quick-draw — wait for the signal, first to shoot scores!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🤠',
  },
  {
    id: 'capture',
    title: 'Capture',
    description: 'Stand on zones to capture them — most zones at time up wins!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🏴',
  },
  {
    id: 'bombs',
    title: 'Bombs',
    description: 'Place bombs that explode in a cross — don\'t get caught in the blast!',
    minPlayers: 2,
    maxPlayers: 4,
    icon: '💣',
  },
  {
    id: 'color-match',
    title: 'Color Match',
    description: 'Press the direction matching the display color, not the word! Speed game.',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🎨',
  },
  {
    id: 'survive',
    title: 'Survive',
    description: 'Dodge projectiles from all edges — waves get faster! Last alive wins.',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '☠️',
  },
  {
    id: 'climber',
    title: 'Climber',
    description: 'Auto-scrolling vertical climb — jump between platforms, don\'t fall!',
    minPlayers: 2,
    maxPlayers: 4,
    icon: '🧗',
  },
  {
    id: 'simon',
    title: 'Simon',
    description: 'Watch the color pattern, then repeat it. Wrong move = eliminated!',
    minPlayers: 2,
    maxPlayers: 8,
    icon: '🧠',
  },
  {
    id: 'tetris',
    title: 'Tetris',
    description: 'Tetriminos fall — clear lines, send garbage, earn coins/gems/stars! Classic, Battle & Co-op.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🧱',
  },
  {
    id: 'worms',
    title: 'Worms',
    description: 'Real-time artillery action — move, aim, shoot simultaneously! Destructible terrain, explosions & team tactics.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🪱',
  },
  {
    id: 'no-time-to-relax',
    title: 'No Time To Relax',
    description: 'Manage work, life & fun in a vacation town! Balance energy, happiness, money & stress. VS, co-op or chill.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏖️',
  },
  {
    id: 'ultimate-chicken-horse',
    title: 'Ultimate Chicken Horse',
    description: 'Platform builder / racer — place traps & platforms, then race to the goal! Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🐔',
  },
  {
    id: 'police-stories',
    title: 'Police Stories',
    description: 'Top-down tactical shooter — breach rooms, arrest enemies, rescue hostages! Co-op raid & VS cops-and-robbers.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🚔',
  },
  {
    id: 'sensible-soccer',
    title: 'Sensible Soccer',
    description: 'Top-down football — dribble, pass, shoot & tackle! Quick match, tournament & co-op vs AI. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '⚽',
  },
  {
    id: 'river-city-girls',
    title: 'River City Girls',
    description: 'Side-scrolling beat \'em up — punch, kick & combo your way through waves of enemies! Story co-op, VS brawl & survival. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '👊',
  },
  {
    id: 'uplink',
    title: 'Uplink',
    description: 'Hacking simulation — hack servers, steal data, avoid traces! Contracts, VS hack race & co-op heist. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '💻',
  },
  {
    id: 'swords-and-sandals',
    title: 'Swords & Sandals',
    description: 'Real-time gladiator combat — attack, block, jump & special moves! Arena VS, co-op tournament & survival. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '⚔️',
  },
  {
    id: 'battle-of-wesnoth',
    title: 'Battle of Wesnoth',
    description: 'Real-time hex strategy — recruit units, capture villages & conquer! Skirmish, co-op campaign & survival. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏰',
  },
  {
    id: 'adventure-capitalist',
    title: 'Adventure Capitalist',
    description: 'Idle/clicker investment game — buy businesses, hire managers, prestige for multipliers! VS race, co-op target & free play. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '💰',
  },
  {
    id: 'might-and-magic',
    title: 'Might & Magic',
    description: 'First-person party RPG dungeon crawler — explore grid dungeons, fight monsters, loot & level up! Solo, co-op & VS arena. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🧙',
  },
  {
    id: 'oil-imperium',
    title: 'Oil Imperium',
    description: 'Oil tycoon economic game — buy land, drill wells, build refineries, manipulate markets! VS mogul, co-op venture & free drill. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🛢️',
  },
  {
    id: 'transport-tycoon',
    title: 'Transport Tycoon',
    description: 'Transport network builder — connect cities, manage vehicles, deliver cargo! VS tycoon, co-op network & sandbox. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🚂',
  },
  {
    id: 'sim-city',
    title: 'SimCity',
    description: 'Top-down city builder — zone residential, commercial & industrial, build roads & power, grow population! VS mayor, co-op city & free build. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏙️',
  },
  {
    id: 'rts',
    title: 'RTS Command',
    description: 'Classic fast RTS — base building, resource gathering, army building & era advancement through 4 ages! VS deathmatch, co-op campaign & skirmish. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '⚔️',
  },
  {
    id: 'settlers',
    title: 'Settlers',
    description: 'Settlers-style builder — place buildings & set priorities, workers do everything automatically! VS conquest, co-op settlement & free build. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏘️',
  },
  {
    id: 'pokemon',
    title: 'Pokémon',
    description: 'Creature collector & real-time battler — explore the overworld, catch creatures, beat gyms & the champion! VS, co-op & adventure. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🐾',
  },
  {
    id: 'civilization',
    title: 'Civilization',
    description: '4X strategy — build cities, research techs, conquer enemies! Domination, science & score victory. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏛️',
  },
  {
    id: 'league-of-legends',
    title: 'League of Legends',
    description: 'Top-down MOBA — 3 lanes, jungle, towers, minions & champions! Level up, buy items, cast abilities, destroy the enemy Nexus. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏟️',
  },
  {
    id: 'shmup',
    title: 'Shmup',
    description: 'Classic vertical scrolling shoot \'em up — dodge bullets, destroy waves, beat bosses! Arcade, VS score & co-op campaign. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🚀',
  },
  {
    id: 'auto-survivors',
    title: 'Auto Survivors',
    description: 'Vampire Survivors-style auto-shoot & auto-gather — survive waves, collect loot, level up with random upgrades! Gather, survival & combo modes. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🧟',
  },
  {
    id: 'doom',
    title: 'Doom',
    description: 'Doom-inspired FPS with raycasting — shoot enemies, find secrets, clear levels! Campaign, VS deathmatch & co-op survival. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🔫',
  },
  {
    id: 'memo',
    title: 'Memo',
    description: 'Real-time memory card game — race to match pairs, grab power-ups, build combos! VS race, co-op clear & solo challenge. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🃏',
  },
  {
    id: 'drag-racing',
    title: 'Drag Racing',
    description: 'Quarter-mile drag racing — upgrade your car, nail the perfect shift, hit NOS! Single race, tournament & co-op relay. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏎️',
  },
  {
    id: 'car-dodge',
    title: 'Car Dodge',
    description: 'Handheld-style lane dodger — swerve between obstacles, collect fuel & coins! Endless, VS distance & co-op survival. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🚗',
  },
  {
    id: 'star-merchant',
    title: 'Star Merchant',
    description: 'Space trading — fly between planets, buy low, sell high, dodge pirates! Free trade, VS wealth & co-op target. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🛸',
  },
  {
    id: 'master-of-orion',
    title: 'Master of Orion',
    description: '4X space strategy — colonize planets, build fleets, research tech, conquer the galaxy! Conquest, science & timed score. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🌌',
  },
  {
    id: 'puzzle',
    title: 'Puzzle',
    description: 'Sliding tile puzzle race — arrange tiles, build combos, use power-ups! Race, VS puzzle & co-op solve. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🧩',
  },
  {
    id: 'pipes',
    title: 'Pipes',
    description: 'Rotational pipe puzzle — connect source to target before water floods! Puzzle, VS race & co-op plumb. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🔧',
  },
  {
    id: 'sim-tower',
    title: 'Sim Tower',
    description: 'Build & manage a skyscraper — offices, shops, residences, elevators! Sandbox, VS rating & co-op tower. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🏢',
  },
  {
    id: 'icy-tower',
    title: 'Icy Tower',
    description: 'Vertical platformer — jump ever higher, combo-bounce off walls, don\'t fall! Climb, VS height & co-op climb. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🧊',
  },
  {
    id: 'ships',
    title: 'Ships',
    description: 'Naval combat — fire broadsides, dodge enemies, collect treasure! Adventure, VS naval & co-op pirates. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '⛵',
  },
  {
    id: 'horizon-chase',
    title: 'Horizon Chase',
    description: 'Retro pseudo-3D racing — change lanes, dodge traffic, grab fuel! Grand prix, VS race & co-op relay. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🛣️',
  },
  {
    id: 'escape-room',
    title: 'Escape Room',
    description: 'Puzzle room series — solve riddles, find keys, escape before time runs out! Adventure, VS race & co-op escape. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🔐',
  },
  {
    id: 'spore',
    title: 'Spore',
    description: 'Eat & grow — consume smaller creatures, avoid bigger ones, screen zooms out as you grow! Survival, VS biggest & co-op size. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🦠',
  },
  {
    id: 'auction-house',
    title: 'Auction House',
    description: 'Run an auction house — buy from garage sales, appraise, restore & sell at auction! Career, VS tycoon & co-op dealers. Coins, gems & stars.',
    minPlayers: 1,
    maxPlayers: 4,
    icon: '🔨',
  },
]
