/**
 * JoinRoomPage — secondary browser window that joins a multi-window game room.
 *
 * URL: /mini-games/join/:roomId
 *
 * Flow:
 *  1. User opens this URL (or clicks the link generated by the host lobby)
 *  2. They pick a name/color and press Join
 *  3. BroadcastChannel connects to the host window's room
 *  4. Once joined, this window captures keyboard/gamepad input
 *     and sends it to the host for processing
 *  5. The host treats remote players like any other PlayerSlot
 */
import { useState, useEffect, useCallback, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useMultiWindowClient } from './useMultiWindow'
import { PLAYER_COLORS, PLAYER_NAMES } from './types'
import { KEY_LOOKUP, ACTION_KEYS, gamepadDir } from './inputMaps'
import { useGamepads } from './useGamepads'
import type { InputMessage } from './multiWindow'
import styles from './JoinRoom.module.css'

export default function JoinRoomPage() {
  const { roomId } = useParams<{ roomId: string }>()
  const { t } = useTranslation()
  const navigate = useNavigate()
  const {
    connected, phase, roster,
    joinRoom, leaveRoom, sendInput,
  } = useMultiWindowClient()

  const [name, setName] = useState<string>(PLAYER_NAMES[0])
  const [color, setColor] = useState<string>(PLAYER_COLORS[0])
  const [joining, setJoining] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Input state ref for continuous sending
  const inputRef = useRef<InputMessage['input']>({ dx: 0, dy: 0, action: false, action2: false })
  const pads = useGamepads()
  const padIndexRef = useRef<number | null>(null)

  // ── Join handler ───────────────────────────────────────────────────────

  const handleJoin = useCallback(() => {
    if (!roomId) {
      setError(t('multiWindow.invalidRoom', 'Invalid room code'))
      return
    }
    setJoining(true)
    setError(null)
    joinRoom(roomId, name, color)

    // Timeout if no ack within 3s
    const timeout = setTimeout(() => {
      setJoining(false)
      setError(t('multiWindow.noHost', 'Could not find host. Make sure the host window is open.'))
    }, 3000)

    return () => clearTimeout(timeout)
  }, [roomId, name, color, joinRoom, t])

  // Clear joining state on connect
  useEffect(() => {
    if (connected) setJoining(false)
  }, [connected])

  // ── Input capture (only when connected + in game phase) ────────────────

  useEffect(() => {
    if (!connected) return
    const pressed = new Set<string>()

    const onKeyDown = (e: KeyboardEvent) => {
      pressed.add(e.key)
      updateInput()
    }
    const onKeyUp = (e: KeyboardEvent) => {
      pressed.delete(e.key)
      updateInput()
    }

    function updateInput() {
      let dx = 0, dy = 0, action = false, action2 = false

      // Check all keyboard mappings
      for (const key of pressed) {
        const mapped = KEY_LOOKUP.get(key)
        if (mapped) {
          dx += mapped.dir.dx
          dy += mapped.dir.dy
        }
        if (ACTION_KEYS.has(key)) action = true
        // LB equivalent: Shift or Q
        if (key === 'Shift' || key === 'q' || key === 'Q') action2 = true
      }

      // Clamp
      dx = Math.max(-1, Math.min(1, dx))
      dy = Math.max(-1, Math.min(1, dy))

      inputRef.current = { dx, dy, action, action2 }
    }

    window.addEventListener('keydown', onKeyDown)
    window.addEventListener('keyup', onKeyUp)
    return () => {
      window.removeEventListener('keydown', onKeyDown)
      window.removeEventListener('keyup', onKeyUp)
    }
  }, [connected])

  // Gamepad polling + send input at 60fps
  useEffect(() => {
    if (!connected) return
    let raf = 0

    const tick = () => {
      // Check gamepads
      const gamepads = navigator.getGamepads?.() ?? []
      for (let i = 0; i < gamepads.length; i++) {
        const gp = gamepads[i]
        if (!gp) continue
        if (padIndexRef.current === null) {
          // Auto-detect first active gamepad
          if (gp.buttons.some(b => b.pressed)) padIndexRef.current = i
          continue
        }
        if (i !== padIndexRef.current) continue

        const dir = gamepadDir({
          up: gp.axes[1] < -0.5 || gp.buttons[12]?.pressed,
          down: gp.axes[1] > 0.5 || gp.buttons[13]?.pressed,
          left: gp.axes[0] < -0.5 || gp.buttons[14]?.pressed,
          right: gp.axes[0] > 0.5 || gp.buttons[15]?.pressed,
        })

        const prev = inputRef.current
        const newInput: InputMessage['input'] = {
          dx: dir?.dx ?? 0,
          dy: dir?.dy ?? 0,
          action: gp.buttons[0]?.pressed ?? false,       // A
          action2: gp.buttons[4]?.pressed ?? false,      // LB
        }

        // Only update if changed
        if (newInput.dx !== prev.dx || newInput.dy !== prev.dy ||
            newInput.action !== prev.action || newInput.action2 !== prev.action2) {
          inputRef.current = newInput
        }
      }

      // Send current input
      sendInput(inputRef.current)
      raf = requestAnimationFrame(tick)
    }

    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [connected, sendInput, pads])

  // ── Render: Disconnected ───────────────────────────────────────────────

  if (phase === 'disconnected') {
    return (
      <div className={styles.container}>
        <div className={styles.card}>
          <h1 className={styles.title}>❌ {t('multiWindow.disconnected', 'Disconnected')}</h1>
          <p className={styles.subtitle}>
            {t('multiWindow.hostLeft', 'The host window was closed.')}
          </p>
          <button className={styles.btn} onClick={() => navigate('/mini-games')}>
            {t('miniGames.backToMenu', 'Back to Menu')}
          </button>
        </div>
      </div>
    )
  }

  // ── Render: Connected — show active state ──────────────────────────────

  if (connected) {
    const isInGame = phase === 'game' || phase === 'title';
    return (
      <div className={styles.container}>
        <div className={styles.card}>
          <div className={styles.connectedBadge}>
            <div className={styles.statusDot} />
            {t('multiWindow.connected', 'Connected')}
          </div>
          <h1 className={styles.title}>🎮 {name}</h1>
          <p className={styles.subtitle}>
            {t('multiWindow.room', 'Room')}: <span className={styles.roomCode}>{roomId}</span>
          </p>
          {isInGame ? (
            <p className={styles.phaseLabel} style={{ color: '#0f0', fontWeight: 700 }}>
              🟢 {t('multiWindow.gameActive', 'Game in progress — your input is live!')}
            </p>
          ) : (
            <p className={styles.phaseLabel}>
              {t('multiWindow.phase', 'Phase')}: <strong>{phase}</strong>
            </p>
          )}

          {roster.length > 0 && (
            <div className={styles.roster}>
              <h3>{t('multiWindow.players', 'Players')}</h3>
              {roster.map((p, i) => (
                <div key={i} className={styles.rosterItem}>
                  <span className={styles.rosterDot} style={{ background: p.color }} />
                  <span>{p.name}</span>
                  {p.isHost && <span className={styles.hostBadge}>HOST</span>}
                </div>
              ))}
            </div>
          )}

          <div className={styles.inputHint}>
            <p>{t('multiWindow.inputHint', 'Use keyboard or gamepad — input is sent to the host window')}</p>
            <div className={styles.inputVis}>
              <span className={inputRef.current.dx < 0 ? styles.active : ''}>←</span>
              <span className={inputRef.current.dy < 0 ? styles.active : ''}>↑</span>
              <span className={inputRef.current.dy > 0 ? styles.active : ''}>↓</span>
              <span className={inputRef.current.dx > 0 ? styles.active : ''}>→</span>
              <span className={inputRef.current.action ? styles.active : ''}>A</span>
            </div>
          </div>

          <button className={styles.btnSecondary} onClick={() => { leaveRoom(); navigate('/mini-games') }}>
            {t('multiWindow.leave', 'Leave Room')}
          </button>
        </div>
      </div>
    )
  }

  // ── Render: Join form ──────────────────────────────────────────────────

  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <h1 className={styles.title}>🖥️ {t('multiWindow.joinTitle', 'Join Game Room')}</h1>
        <p className={styles.subtitle}>
          {t('multiWindow.room', 'Room')}: <span className={styles.roomCode}>{roomId}</span>
        </p>

        <div className={styles.field}>
          <label>{t('multiWindow.yourName', 'Your Name')}</label>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            className={styles.input}
            maxLength={20}
          />
        </div>

        <div className={styles.field}>
          <label>{t('multiWindow.yourColor', 'Your Color')}</label>
          <div className={styles.colorPicker}>
            {PLAYER_COLORS.map((c) => (
              <button
                key={c}
                className={`${styles.colorSwatch} ${c === color ? styles.colorSelected : ''}`}
                style={{ background: c }}
                onClick={() => setColor(c)}
              />
            ))}
          </div>
        </div>

        {error && <p className={styles.error}>{error}</p>}

        <button
          className={styles.btn}
          onClick={handleJoin}
          disabled={joining || !name.trim()}
        >
          {joining
            ? t('multiWindow.connecting', 'Connecting…')
            : t('multiWindow.join', 'Join Room')}
        </button>

        <button className={styles.btnSecondary} onClick={() => navigate('/mini-games')}>
          {t('miniGames.back', 'Back')}
        </button>
      </div>
    </div>
  )
}
