using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MediatR;
using AudioVerse.Infrastructure.Storage;

namespace AudioVerse.API.Areas.Events.Controllers
{
    /// <summary>
    /// Event videos — upload, streaming, thumbnails, tags.
    /// </summary>
    [ApiController]
    [Route("api/events")]
    [Authorize]
    [Produces("application/json")]
    [Tags("Events - Videos")]
    public class EventVideosController : ControllerBase
    {
        private readonly IMediator _mediator;

        public EventVideosController(IMediator mediator) => _mediator = mediator;

        /// <summary>Upload a video for an event.</summary>
        [HttpPost("{eventId:int}/videos")]
        [Consumes("multipart/form-data")]
        [RequestSizeLimit(500_000_000)]
        public async Task<IActionResult> AddVideo(int eventId, IFormFile file, [FromForm] string? title, [FromForm] int? userId)
        {
            if (file == null || file.Length == 0) return BadRequest(new { Message = "File is required" });

            var fs = HttpContext.RequestServices.GetRequiredService<IFileStorage>();
            var ext = Path.GetExtension(file.FileName)?.ToLowerInvariant() ?? ".mp4";
            var key = $"events/{eventId}/{Guid.NewGuid()}{ext}";
            await fs.EnsureBucketExistsAsync("ev-videos");

            var bytes = new byte[file.Length];
            using (var s = file.OpenReadStream()) await s.ReadExactlyAsync(bytes);
            using var ms = new MemoryStream(bytes);
            await fs.UploadAsync("ev-videos", key, ms, file.ContentType ?? "video/mp4");

            var video = new AudioVerse.Domain.Entities.Events.EventVideo
            {
                EventId = eventId,
                ObjectKey = key,
                ContentType = file.ContentType ?? "video/mp4",
                FileSizeBytes = file.Length,
                Title = title,
                UploadedByUserId = userId
            };
            var id = await _mediator.Send(new AudioVerse.Application.Commands.Events.AddEventVideoCommand(video));
            return Created($"/api/events/{eventId}/videos/{id}", new { Id = id, Key = key });
        }

        /// <summary>Get videos for an event.</summary>
        [HttpGet("{eventId:int}/videos")]
        public async Task<IActionResult> GetVideos(int eventId)
            => Ok(await _mediator.Send(new AudioVerse.Application.Queries.Events.GetEventVideosQuery(eventId)));

        /// <summary>Stream a video (supports HTTP Range requests for seeking).</summary>
        [HttpGet("{eventId:int}/videos/{id:int}/stream")]
        [AllowAnonymous]
        public async Task<IActionResult> StreamVideo(int eventId, int id)
        {
            var videos = await _mediator.Send(new AudioVerse.Application.Queries.Events.GetEventVideosQuery(eventId));
            var video = videos.FirstOrDefault(v => v.Id == id);
            if (video == null) return NotFound();

            var fs = HttpContext.RequestServices.GetRequiredService<IFileStorage>();
            var stream = await fs.DownloadAsync("ev-videos", video.ObjectKey);
            if (stream == null) return NotFound();

            return File(stream, video.ContentType, enableRangeProcessing: true);
        }

        /// <summary>Delete a video.</summary>
        [HttpDelete("{eventId:int}/videos/{id:int}")]
        public async Task<IActionResult> DeleteVideo(int eventId, int id)
            => await _mediator.Send(new AudioVerse.Application.Commands.Events.DeleteEventVideoCommand(id)) ? NoContent() : NotFound();

        /// <summary>Upload video thumbnail (generated by frontend from a selected frame).</summary>
        [HttpPost("{eventId:int}/videos/{videoId:int}/thumbnail")]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> UploadVideoThumbnail(int eventId, int videoId, IFormFile file)
        {
            if (file == null || file.Length == 0) return BadRequest(new { Message = "File is required" });

            var fs = HttpContext.RequestServices.GetRequiredService<IFileStorage>();
            var key = $"events/{eventId}/thumbs/vid-{videoId}-{Guid.NewGuid()}.png";
            await fs.EnsureBucketExistsAsync("ev-videos");
            var bytes = new byte[file.Length];
            using (var s = file.OpenReadStream()) await s.ReadExactlyAsync(bytes);
            using var ms = new MemoryStream(bytes);
            await fs.UploadAsync("ev-videos", key, ms, "image/png");

            await _mediator.Send(new AudioVerse.Application.Commands.Events.SetVideoThumbnailCommand(videoId, key));
            return Ok(new { Success = true, ThumbnailKey = key });
        }

        /// <summary>Serve video thumbnail.</summary>
        [HttpGet("{eventId:int}/videos/{videoId:int}/thumbnail")]
        [AllowAnonymous]
        public async Task<IActionResult> GetVideoThumbnail(int eventId, int videoId)
        {
            var videos = await _mediator.Send(new AudioVerse.Application.Queries.Events.GetEventVideosQuery(eventId));
            var video = videos.FirstOrDefault(v => v.Id == videoId);
            if (video == null || string.IsNullOrEmpty(video.ThumbnailKey)) return NotFound();

            var fs = HttpContext.RequestServices.GetRequiredService<IFileStorage>();
            var stream = await fs.DownloadAsync("ev-videos", video.ThumbnailKey);
            return stream != null ? File(stream, "image/png") : NotFound();
        }

        /// <summary>Tag a person on a video (with coordinates and timestamp).</summary>
        [HttpPost("{eventId:int}/videos/{videoId:int}/tags")]
        public async Task<IActionResult> AddVideoTag(int eventId, int videoId, [FromBody] AudioVerse.Domain.Entities.Events.EventMediaTag tag)
        {
            tag.VideoId = videoId;
            var id = await _mediator.Send(new AudioVerse.Application.Commands.Events.AddEventMediaTagCommand(tag));
            return Created($"/api/events/{eventId}/videos/{videoId}/tags/{id}", new { Id = id });
        }

        /// <summary>Get tags on a video.</summary>
        [HttpGet("{eventId:int}/videos/{videoId:int}/tags")]
        public async Task<IActionResult> GetVideoTags(int eventId, int videoId)
            => Ok(await _mediator.Send(new AudioVerse.Application.Queries.Events.GetVideoTagsQuery(videoId)));

        /// <summary>Delete a tag from a video.</summary>
        [HttpDelete("{eventId:int}/videos/{videoId:int}/tags/{tagId:int}")]
        public async Task<IActionResult> DeleteVideoTag(int eventId, int videoId, int tagId)
            => await _mediator.Send(new AudioVerse.Application.Commands.Events.DeleteEventMediaTagCommand(tagId)) ? NoContent() : NotFound();
    }
}
