/**
 * translate-de.cjs
 * Translates all untranslated English values in de.json to German.
 * Usage: node scripts/translate-de.cjs
 */
const fs = require('fs');
const path = require('path');

const EN_PATH = path.resolve(__dirname, '..', 'src', 'i18n', 'locales', 'en.json');
const DE_PATH = path.resolve(__dirname, '..', 'src', 'i18n', 'locales', 'de.json');

// ─────────────────────────────────────────────
// Comprehensive English → German dictionary
// ─────────────────────────────────────────────
const dictionary = {
  // ── Format strings / technical tokens kept as-is ──
  "#rrggbb": "#rrggbb",
  "1/16": "1/16",
  "ABCD-1234": "ABCD-1234",
  "A/B/1": "A/B/1",
  "ID": "ID",
  "IP": "IP",
  "OTP": "OTP",
  "URL": "URL",
  "MIDI": "MIDI",
  "JSON": "JSON",
  "BPM": "BPM",
  "BPM:": "BPM:",
  "BLIK": "BLIK",
  "LFO": "LFO",
  "LIVE": "LIVE",
  "RMS:": "RMS:",
  "DJ": "DJ",
  "OK": "OK",
  "PvP": "PvP",
  "Lv.": "Lv.",
  "Vol": "Lautst.",
  "Pts": "Pkt.",
  "vs": "vs",
  "{{count}} songs": "{{count}} Songs",
  "{{page}} / {{total}}": "{{page}} / {{total}}",
  "{{sec}}s": "{{sec}}s",
  "Zone: {{seconds}}s": "Zone: {{seconds}}s",
  "Party #{{id}}": "Party #{{id}}",
  "Song #{{id}}": "Song #{{id}}",
  "Playlist #{{id}}": "Playlist #{{id}}",
  "Player {{id}}": "Spieler {{id}}",
  "Team {{n}}": "Team {{n}}",
  "Max. {{count}} characters": "Max. {{count}} Zeichen",
  "Min. {{count}} characters": "Min. {{count}} Zeichen",
  "Exported to {{platform}}!": "Zu {{platform}} exportiert!",
  "Token #{{id}} triggered at {{time}}": "Token #{{id}} ausgelöst um {{time}}",
  "Valid from {{from}} to {{to}}": "Gültig von {{from}} bis {{to}}",
  "Total subscriptions: {{count}}": "Abonnements insgesamt: {{count}}",
  "Welcome, {{username}}": "Willkommen, {{username}}",
  "Unsubscribe from {{title}}?": "{{title}} abbestellen?",
  "{{count}} notes in {{layers}} layers": "{{count}} Noten in {{layers}} Ebenen",

  // ── Time values kept as-is ──
  " +5s": " +5s",
  " -5s": " -5s",

  // ── Game names (proper nouns, kept mostly as-is) ──
  "Adventure Capitalist": "Adventure Capitalist",
  "Battle of Wesnoth": "Battle of Wesnoth",
  "Empire RTS": "Empire RTS",
  "Fallout": "Fallout",
  "GTA 2": "GTA 2",
  "Heroes of Might & Magic": "Heroes of Might & Magic",
  "Horizon Chase": "Horizon Chase",
  "Icy Tower": "Icy Tower",
  "League of Legends": "League of Legends",
  "Magic Decks TCG": "Magic Decks TCG",
  "Magic The Gathering": "Magic The Gathering",
  "Master of Orion": "Master of Orion",
  "Might & Magic": "Might & Magic",
  "No Time To Relax": "No Time To Relax",
  "Oil Imperium": "Oil Imperium",
  "Overcooked": "Overcooked",
  "Police Stories": "Police Stories",
  "River City Girls": "River City Girls",
  "Sensible Soccer": "Sensible Soccer",
  "SimCity": "SimCity",
  "SimTower": "SimTower",
  "Swords & Sandals": "Swords & Sandals",
  "Tetris": "Tetris",
  "Tooth & Tail": "Tooth & Tail",
  "Transport Tycoon": "Transport Tycoon",
  "Ultimate Chicken Horse": "Ultimate Chicken Horse",
  "Worms": "Worms",
  "Eight Minute Empire": "Eight Minute Empire",
  "Spore": "Spore",
  "Star Merchant": "Star Merchant",
  "Uplink": "Uplink",

  // ── Common UI actions & labels ──
  "Save": "Speichern",
  "Cancel": "Abbrechen",
  "Delete": "Löschen",
  "Edit": "Bearbeiten",
  "Add": "Hinzufügen",
  "Remove": "Entfernen",
  "Close": "Schließen",
  "Back": "Zurück",
  "Next": "Weiter",
  "Search": "Suche",
  "Reset": "Zurücksetzen",
  "Confirm": "Bestätigen",
  "Yes": "Ja",
  "No": "Nein",
  "Error": "Fehler",
  "Warning": "Warnung",
  "Info": "Info",
  "Loading...": "Wird geladen...",
  "Done": "Fertig",
  "Status": "Status",
  "Status:": "Status:",
  "Actions": "Aktionen",
  "Settings": "Einstellungen",
  "Details": "Details",
  "Description": "Beschreibung",
  "Title": "Titel",
  "Name": "Name",
  "Type": "Typ",
  "Date": "Datum",
  "Duration": "Dauer",
  "Size": "Größe",
  "Total": "Gesamt",
  "None": "Keine",
  "All": "Alle",
  "Select": "Auswählen",
  "Selected": "Ausgewählt",
  "Open": "Öffnen",
  "Create": "Erstellen",
  "Update": "Aktualisieren",
  "Refresh": "Aktualisieren",
  "Upload": "Hochladen",
  "Download": "Herunterladen",
  "Export": "Exportieren",
  "Import": "Importieren",
  "Preview": "Vorschau",
  "Undo": "Rückgängig",
  "Redo": "Wiederherstellen",
  "Start": "Start",
  "Stop": "Stopp",
  "Play": "Abspielen",
  "Pause": "Pause",
  "Continue": "Fortfahren",
  "Send": "Senden",
  "Submit Review": "Bewertung absenden",
  "Post": "Beitrag",
  "Reply": "Antworten",
  "Clear": "Leeren",
  "Copy share link": "Freigabelink kopieren",
  "Rename": "Umbenennen",
  "Duplicate": "Duplizieren",
  "Convert": "Konvertieren",
  "Browse": "Durchsuchen",
  "Explore": "Erkunden",
  "Generate": "Generieren",
  "Join": "Beitreten",
  "Like": "Gefällt mir",
  "Rate": "Bewerten",
  "Report": "Melden",
  "Revert": "Zurücksetzen",
  "Skip": "Überspringen",
  "Prev": "Zurück",
  "Previous": "Zurück",
  "Previous track": "Vorheriger Track",
  "Next track": "Nächster Track",
  "Restart": "Neustart",
  "Active": "Aktiv",
  "Complete": "Abschließen",
  "Completed": "Abgeschlossen",
  "Closed": "Geschlossen",
  "Locked": "Gesperrt",
  "Saved": "Gespeichert",
  "Sent": "Gesendet",
  "Ready": "Bereit",
  "Failed": "Fehlgeschlagen",
  "Visible": "Sichtbar",
  "Public": "Öffentlich",
  "Online": "Online",
  "On": "Ein",
  "Off": "Aus",
  "Auto": "Auto",
  "Mode": "Modus",
  "Mode:": "Modus:",
  "Mode Type": "Modustyp",
  "Normal": "Normal",
  "Simple": "Einfach",
  "Basic": "Einfach",
  "Complex": "Komplex",
  "Standard": "Standard",
  "Custom name": "Eigener Name",
  "Email": "E-Mail",
  "Username": "Benutzername",
  "Password Requirements": "Passwortanforderungen",
  "Password Requirements:": "Passwortanforderungen:",
  "Login": "Anmelden",
  "Sign Up": "Registrieren",
  "Confirm Password": "Passwort bestätigen",
  "Current Password": "Aktuelles Passwort",
  "New Password": "Neues Passwort",
  "Change Password": "Passwort ändern",
  "Language": "Sprache",
  "Zoom": "Zoom",
  "Timestamp": "Zeitstempel",
  "Link": "Link",
  "Sort": "Sortieren",
  "Filter Songs": "Songs filtern",
  "Input": "Eingabe",
  "Input Type": "Eingabetyp",
  "Output": "Ausgabe",
  "Format": "Format",
  "Amount": "Betrag",
  "Quantity": "Menge",
  "Price": "Preis",
  "Priority": "Priorität",
  "Color": "Farbe",
  "Style": "Stil",
  "Scale": "Skala",
  "Step": "Schritt",
  "Phase": "Phase",
  "Key": "Tonart",
  "Note": "Note",
  "Unit": "Einheit",
  "Source": "Quelle",
  "Year": "Jahr",
  "Second": "Sekunde",
  "Message": "Nachricht",
  "Comments": "Kommentare",
  "Parameter": "Parameter",
  "Parameters": "Parameter",
  "Curve": "Kurve",
  "Pattern": "Muster",
  "Threshold": "Schwellenwert",
  "Gain": "Verstärkung",
  "Balance": "Balance",
  "Pan": "Pan",

  // ── Longer UI actions ──
  " 3D Lift": " 3D-Anhebung",
  " Click to enable audio": " Klicken, um Audio zu aktivieren",
  " Detect (2D)": " Erkennen (2D)",
  " Generate": " Generieren",
  " Load": " Laden",
  " No artist/title data for search": " Keine Künstler-/Titeldaten für die Suche",
  " Not found on YouTube": " Nicht auf YouTube gefunden",
  " Pause": " Pause",
  " Play": " Abspielen",
  " Pose Game": " Posen-Spiel",
  " Save": " Speichern",
  " Search error": " Suchfehler",
  " Searching YouTube...": " YouTube wird durchsucht...",
  " Stop": " Stopp",
  " Track (Video)": " Verfolgen (Video)",
  "(leave empty for unlimited)": "(leer lassen für unbegrenzt)",
  "(no entries)": "(keine Einträge)",
  "(no title)": "(kein Titel)",
  "(unknown)": "(unbekannt)",
  "+ Add": "+ Hinzufügen",
  "+ Clip": "+ Clip",
  "+ Delay": "+ Verzögerung",
  "+ EQ3": "+ EQ3",
  "+ New Organization": "+ Neue Organisation",
  "+ Reverb": "+ Hall",

  // ── Time durations ──
  "2 Minutes": "2 Minuten",
  "3 Minutes": "3 Minuten",
  "5 Minutes": "5 Minuten",
  "7 Minutes": "7 Minuten",
  "8 Minutes": "8 Minuten",
  "10 Minutes": "10 Minuten",
  "12 Minutes": "12 Minuten",
  "12 characters minimum": "Mindestens 12 Zeichen",

  // ── DAW / Audio ──
  "2D  3D Lifting": "2D  3D-Anhebung",
  "3D Model Editor": "3D-Modell-Editor",
  "Audio": "Audio",
  "Audio Analysis": "Audioanalyse",
  "Audio Clips List": "AudioClip-Liste",
  "Audio Layer": "Audio-Ebene",
  "Audio Question": "Audiofrage",
  "Audio Source Properties": "Audio-Quelleneigenschaften",
  "Audio Stem Separation (Demucs)": "Audio-Stem-Trennung (Demucs)",
  "Audio Type": "Audiotyp",
  "AudioClip Library": "AudioClip-Bibliothek",
  "AudioClip added!": "AudioClip hinzugefügt!",
  "Autocorrelation": "Autokorrelation",
  "Available audio devices": "Verfügbare Audiogeräte",
  "Backing Track": "Begleittrack",
  "Bar": "Takt",
  "Bar style": "Balkenstil",
  "Bars": "Takte",
  "Beat": "Beat",
  "CC Automation Lane": "CC-Automationsspur",
  "CREPE (server)": "CREPE (Server)",
  "Channels": "Kanäle",
  "Count-in (bars)": "Einzählen (Takte)",
  "De-Esser": "De-Esser",
  "Drums": "Schlagzeug",
  "EQ Presets": "EQ-Vorlagen",
  "Gate": "Gate",
  "Instrument": "Instrument",
  "Intonation": "Intonation",
  "Intro": "Intro",
  "Metronome": "Metronom",
  "Microphones": "Mikrofone",
  "Octave": "Oktave",
  "Octaves": "Oktaven",
  "Pitch algorithm": "Tonhöhen-Algorithmus",
  "Pitchy (YIN)": "Pitchy (YIN)",
  "Pitchy (local)": "Pitchy (lokal)",
  "Step Sequencer": "Step-Sequenzer",
  "Tempo": "Tempo",
  "Volume": "Lautstärke",
  "Arpeggiator": "Arpeggiator",
  "Music": "Musik",
  "Hanning:": "Hanning:",

  // ── Skin / Theme names ──
  "Amber Kiss": "Bernsteinkuss",
  "Amber Night": "Bernsteinnacht",
  "Cocoa Mist": "Kakaonebel",
  "Coral Veil": "Korallenschleier",
  "Crimson Silk": "Karmesinseide",
  "Desert Rose": "Wüstenrose",
  "Eclipse": "Finsternis",
  "Garnet": "Granat",
  "Honeyed": "Honigfarben",
  "Lavender Haze": "Lavendeldunst",
  "Midnight Bloom": "Mitternachtsblüte",
  "Moonlit Amber": "Mondlicht-Bernstein",
  "Moonshadow": "Mondschatten",
  "Nocturne": "Nocturne",
  "Opal Dusk": "Opaldämmerung",
  "Opaline": "Opalin",
  "Pearl Veil": "Perlenschleier",
  "Rose Whisper": "Rosenflüstern",
  "Rosewood": "Rosenholz",
  "Saffron Glow": "Safranschimmer",
  "Scarlet Lace": "Scharlachspitze",
  "Silk Noir": "Seidenschwarz",
  "Silk Rose": "Seidenrose",
  "Silken Azure": "Seidenblau",
  "Twilight Silk": "Dämmerungsseide",
  "Velour": "Velours",
  "Velvet Night": "Samtnacht",
  "Velvet Plum": "Samtpflaume",
  "Lava": "Lava",
  "Glow": "Leuchten",

  // ── Skin / Theme descriptions ──
  "A musical, moody night palette with deep contrasts.": "Eine musikalische, stimmungsvolle Nachtpalette mit tiefen Kontrasten.",
  "Chocolate-inspired warm browns and creams.": "Von Schokolade inspirierte warme Braun- und Cremetöne.",
  "Cool, soft shadowy hues for a calm UI.": "Kühle, sanfte Schattentöne für eine ruhige Oberfläche.",
  "Deep purples and rich plum tones.": "Tiefe Violetttöne und satte Pflaumennuancen.",
  "Deep, contrasting tones reminiscent of an eclipse.": "Tiefe, kontrastierende Töne, die an eine Sonnenfinsternis erinnern.",
  "Delicate coral and blush tones with warmth.": "Zarte Korallen- und Rougetöne mit Wärme.",
  "Delicate petal-inspired rosy shades.": "Zarte, blütenblattinspirierte Rosatöne.",
  "Earthy, desert-inspired warm tones.": "Erdige, wüsteninspirierte Warmtöne.",
  "Elegant black with refined, high-contrast accents.": "Elegantes Schwarz mit edlen, kontrastreichen Akzenten.",
  "Honeyed, cozy colors with warm accents.": "Honigfarbene, gemütliche Farben mit warmen Akzenten.",
  "Intense, sensual palette with bold accents.": "Intensive, sinnliche Farbpalette mit kräftigen Akzenten.",
  "Lacy scarlet reds with refined contrast.": "Zarte Scharlachrottöne mit edlem Kontrast.",
  "Minimalist, high-contrast monochrome styling.": "Minimalistisches, kontrastreiches Monochrom-Styling.",
  "Night-blooming floral palette with moody contrasts.": "Nachtblühende florale Farbpalette mit stimmungsvollen Kontrasten.",
  "Nocturnal silky tones with twilight highlights.": "Nächtliche seidige Töne mit Dämmerungsakzenten.",
  "Pearlescent, semi-translucent soft shades.": "Perlmuttartige, halbtransparente sanfte Schattierungen.",
  "Rich jewel-red tones for dramatic emphasis.": "Satte Edelsteinrottöne für dramatische Wirkung.",
  "Sensual deep reds with silky contrasts.": "Sinnliche tiefe Rottöne mit seidigen Kontrasten.",
  "Shimmering, cool dusk tones with opalescent highlights.": "Schimmernde, kühle Dämmerungstöne mit opalisierenden Akzenten.",
  "Smooth velvety shades for a luxurious dark UI.": "Glatte, samtige Schattierungen für eine luxuriöse dunkle Oberfläche.",
  "Soft azure and sky-blue tones with airy feel.": "Sanfte Azur- und Himmelblautöne mit luftigem Gefühl.",
  "Soft lavender pastels with a mellow atmosphere.": "Sanfte Lavendel-Pastelltöne mit entspannter Atmosphäre.",
  "Soft, enveloping colors with plush tones.": "Weiche, umhüllende Farben mit samtigen Tönen.",
  "Subtle pearly accents and soft blues.": "Dezente Perlglanz-Akzente und sanfte Blautöne.",
  "Subtle pinks and beiges for a gentle look.": "Dezente Rosa- und Beigetöne für einen sanften Look.",
  "Sweet, warm pastels with cozy accents.": "Süße, warme Pastelltöne mit gemütlichen Akzenten.",
  "Warm moonlit tones with amber highlights.": "Warme Mondlichttöne mit Bernstein-Akzenten.",
  "Warm night-lights and amber glows.": "Warme Nachtlichter und Bernsteinschimmer.",
  "Warm, spice-toned palette with amber highlights.": "Warme, gewürztonige Palette mit Bernstein-Akzenten.",
  "Woodsy, warm hues inspired by natural timber.": "Waldige, warme Farbtöne inspiriert von natürlichem Holz.",

  // ── Admin / Security ──
  "Admin": "Admin",
  "Admin Dashboard": "Admin-Dashboard",
  "Admin Settings": "Admin-Einstellungen",
  "Audit": "Audit",
  "Audit Dashboard": "Audit-Dashboard",
  "Audit Events Trend": "Trend der Audit-Ereignisse",
  "Audit Logs": "Audit-Protokolle",
  "All Audit Logs (Admin)": "Alle Audit-Protokolle (Admin)",
  "My Audit Logs": "Meine Audit-Protokolle",
  "Dashboard": "Dashboard",
  "Honey Tokens": "Honey-Tokens",
  "HoneyToken Management": "HoneyToken-Verwaltung",
  "HoneyTokens": "HoneyTokens",
  "Honeytokens": "Honeytokens",
  "Triggered Honeytokens Trend": "Trend ausgelöster Honeytokens",
  "Triggered Honeytokens:": "Ausgelöste Honeytokens:",
  "Security Analytics": "Sicherheitsanalysen",
  "Security Dashboard": "Sicherheits-Dashboard",
  "More security metrics and analytics coming soon...": "Weitere Sicherheitsmetriken und Analysen folgen bald...",
  "User Management": "Benutzerverwaltung",
  "Users": "Benutzer",
  "Login Attempts": "Anmeldeversuche",
  "Feature Visibility": "Funktions-Sichtbarkeit",
  "Features": "Funktionen",
  "CAPTCHA Type:": "CAPTCHA-Typ:",
  "CAPTCHA loading error": "CAPTCHA-Ladefehler",
  "CAPTCHA validation error": "CAPTCHA-Validierungsfehler",
  "Generate CAPTCHA": "CAPTCHA generieren",
  "Incorrect CAPTCHA answer": "Falsche CAPTCHA-Antwort",
  "Create Token": "Token erstellen",
  "Failed to create token": "Token konnte nicht erstellt werden",
  "Token ID": "Token-ID",
  "Skins": "Skins",

  // ── User / Auth ──
  "Author": "Autor",
  "Creator": "Ersteller",
  "Collaborators": "Mitarbeiter",
  "Current collaborators": "Aktuelle Mitarbeiter",
  "Anonymous": "Anonym",
  "Everyone": "Alle",
  "Your Email": "Deine E-Mail",
  "Your Name": "Dein Name",
  "Your name": "Dein Name",
  "Your Progress": "Dein Fortschritt",
  "Your rank": "Dein Rang",
  "Your comment (optional)...": "Dein Kommentar (optional)...",
  "Your display name (optional)": "Dein Anzeigename (optional)",
  "Change language": "Sprache ändern",
  "Change admin password and other settings": "Admin-Passwort und andere Einstellungen ändern",
  "Configure password policies and security requirements": "Passwortrichtlinien und Sicherheitsanforderungen konfigurieren",
  "Manage users, create new accounts, block/unblock users": "Benutzer verwalten, neue Konten erstellen, Benutzer sperren/entsperren",
  "At least 1 digit": "Mindestens 1 Ziffer",
  "At least 1 special character": "Mindestens 1 Sonderzeichen",
  "At least one digit": "Mindestens eine Ziffer",
  "At least one lowercase letter": "Mindestens ein Kleinbuchstabe",
  "At least one special character": "Mindestens ein Sonderzeichen",
  "At least one uppercase letter": "Mindestens ein Großbuchstabe",
  "Digit": "Ziffer",
  "Password change required at first login!": "Passwortänderung beim ersten Login erforderlich!",
  "Password changed successfully": "Passwort erfolgreich geändert",
  "Password changed successfully!": "Passwort erfolgreich geändert!",
  "Password does not meet requirements": "Passwort erfüllt die Anforderungen nicht",
  "Password requirements updated successfully!": "Passwortanforderungen erfolgreich aktualisiert!",
  "Passwords do not match": "Passwörter stimmen nicht überein",
  "Confirm your new password": "Neues Passwort bestätigen",
  "Enter your current password": "Aktuelles Passwort eingeben",
  "Enter your new password": "Neues Passwort eingeben",
  "New password must be at least 6 characters long": "Neues Passwort muss mindestens 6 Zeichen lang sein",
  "Failed to change password": "Passwort konnte nicht geändert werden",
  "Failed to load password requirements": "Passwortanforderungen konnten nicht geladen werden",
  "Failed to save password requirements": "Passwortanforderungen konnten nicht gespeichert werden",
  "Loading password requirements...": "Passwortanforderungen werden geladen...",
  "No password requirements found": "Keine Passwortanforderungen gefunden",

  // ── Music / Karaoke ──
  "Song": "Song",
  "Songs": "Songs",
  "Album": "Album",
  "Artist": "Künstler",
  "Playlist": "Playlist",
  "Playlists": "Playlists",
  "Karaoke": "Karaoke",
  "Karaoke Campaigns": "Karaoke-Kampagnen",
  "Karaoke Editor (Preview with audio and lyrics)": "Karaoke-Editor (Vorschau mit Audio und Text)",
  "Karaoke Gradient Colors": "Karaoke-Farbverlaufsfarben",
  "Karaoke Ranking": "Karaoke-Rangliste",
  "Karaoke Song Management": "Karaoke-Songverwaltung",
  "Song ID": "Song-ID",
  "Song Metadata": "Song-Metadaten",
  "Song Mini-Games": "Song-Minispiele",
  "Song Picks": "Songauswahlen",
  "Song Title": "Songtitel",
  "Song chosen!": "Song ausgewählt!",
  "Song has no karaoke notes.": "Song hat keine Karaoke-Noten.",
  "Song is missing required data.": "Song fehlen erforderliche Daten.",
  "All Songs": "Alle Songs",
  "All songs": "Alle Songs",
  "Add Song": "Song hinzufügen",
  "Add song": "Song hinzufügen",
  "Add to playlist": "Zur Playlist hinzufügen",
  "Add to queue": "Zur Warteschlange hinzufügen",
  "Change Song": "Song wechseln",
  "Choose a Song": "Song auswählen",
  "No songs found": "Keine Songs gefunden",
  "No songs in pool.": "Keine Songs im Pool.",
  "No songs. Add the first one below.": "Keine Songs. Füge den ersten unten hinzu.",
  "Songs per day": "Songs pro Tag",
  "Total Songs": "Gesamtanzahl Songs",
  "Ranked Songs": "Bewertete Songs",
  "Search songs...": "Songs suchen...",
  "Type to search songs...": "Songs suchen...",
  "Filter by username": "Nach Benutzername filtern",
  "Allow everyone to modify this song": "Allen erlauben, diesen Song zu bearbeiten",
  "This song has no note data. Please pick another song.": "Dieser Song hat keine Notendaten. Bitte wähle einen anderen Song.",
  "Lyrics": "Texte",
  "Melody density": "Melodiedichte",
  "Vocal Effects": "Stimmeffekte",
  "Singing Activity": "Gesangsaktivität",
  "My Singing History": "Mein Gesangsverlauf",
  "No singing history yet. Time to sing! \u{1F3A4}": "Noch kein Gesangsverlauf. Zeit zu singen! \u{1F3A4}",
  "Live Score": "Live-Punktzahl",
  "Live Singing Score": "Live-Gesangspunktzahl",
  "Score": "Punktzahl",
  "Total Score": "Gesamtpunktzahl",
  "Total Points": "Gesamtpunkte",
  "Scoring Parameters": "Bewertungsparameter",
  "Scoring Presets": "Bewertungsvorlagen",
  "Gold Notes Gradient": "Gold-Noten-Farbverlauf",
  "Sung Text Gradient": "Gesungener-Text-Farbverlauf",
  "Timeline Animation": "Zeitleisten-Animation",
  "Ultrastar": "Ultrastar",
  "Search Ultrastar...": "Ultrastar durchsuchen...",
  "Confidence": "Konfidenz",
  "Combo": "Combo",
  "Miss": "Verfehlt",
  "Good": "Gut",
  "Great": "Großartig",
  "Perfect!": "Perfekt!",
  "Jam Session": "Jam-Session",
  "Jitter & Shimmer": "Jitter & Shimmer",
  "Demo (12s)": "Demo (12s)",

  // ── Karaoke long descriptions ──
  "A full-featured digital audio workstation right in your browser. Record, edit, mix, and master with studio-grade tools.": "Eine vollwertige digitale Audio-Workstation direkt in deinem Browser. Aufnehmen, bearbeiten, mischen und mastern mit Studio-Tools.",
  "Analyze and tune karaoke scoring parameters with fixture data": "Karaoke-Bewertungsparameter mit Testdaten analysieren und einstellen",
  "Apply live vocal effects to your microphone. Choose from 20 effects \u2014 stack multiple at once. Hear the results through your speakers in real time.": "Wende Live-Stimmeffekte auf dein Mikrofon an. Wähle aus 20 Effekten \u2014 kombiniere mehrere gleichzeitig. Höre die Ergebnisse in Echtzeit über deine Lautsprecher.",
  "Apply live vocal effects \u2014 chipmunk, robot, echo, and more.": "Wende Live-Stimmeffekte an \u2014 Chipmunk, Roboter, Echo und mehr.",
  "Apply to Song": "Auf Song anwenden",
  "Choose a color preset or create your own custom gradient for sung lyrics.": "Wähle eine Farbvorlage oder erstelle deinen eigenen Farbverlauf für gesungene Texte.",
  "Choose a font for the karaoke timeline canvas and lyrics overlay.": "Wähle eine Schriftart für die Karaoke-Zeitleiste und Textüberlagerung.",
  "Choose how the karaoke timeline animates during singing.": "Wähle, wie die Karaoke-Zeitleiste beim Singen animiert wird.",
  "Classify songs into dance styles, view matches, and analyze audio parameters.": "Klassifiziere Songs nach Tanzstilen, sieh Treffer und analysiere Audioparameter.",
  "Click effects to toggle. Multiple effects can be active simultaneously. Adjust intensity with the slider.": "Klicke auf Effekte, um sie umzuschalten. Mehrere Effekte können gleichzeitig aktiv sein. Intensität mit dem Regler anpassen.",
  "Click or drag & drop to upload an Ultrastar file (.txt)": "Klicken oder per Drag & Drop eine Ultrastar-Datei (.txt) hochladen",
  "Click steps to toggle. Drag velocity bars vertically.": "Klicke auf Schritte zum Umschalten. Ziehe Velocity-Balken vertikal.",
  "Click the link below to download ZIP with stems.": "Klicke auf den Link unten, um ZIP mit Stems herunterzuladen.",
  "Click to draw. Double-click to add/remove points. Drag to draw curves.": "Zum Zeichnen klicken. Doppelklick zum Hinzufügen/Entfernen von Punkten. Ziehen für Kurven.",
  "Drag syllable edges to adjust timing; hold Shift to snap to beat grid.": "Ziehe Silbenränder, um das Timing anzupassen; halte Umschalt gedrückt für Rasterung.",
  "Each line will be added as a separate song.": "Jede Zeile wird als separater Song hinzugefügt.",
  "Edit in Karaoke Editor": "Im Karaoke-Editor bearbeiten",
  "Edit karaoke scoring presets used by the parity harness and live scoring": "Karaoke-Bewertungsvorlagen für den Paritätstest und Live-Bewertung bearbeiten",
  "Edit scoring presets. Changes are saved to backend if available, otherwise to localStorage.": "Bewertungsvorlagen bearbeiten. Änderungen werden im Backend gespeichert, falls verfügbar, sonst im localStorage.",
  "Edit, create, and manage karaoke files with UltraStar-compatible timing, canvas visuals, and AI scoring.": "Bearbeiten, erstellen und verwalten von Karaoke-Dateien mit UltraStar-kompatiblem Timing, Canvas-Visuals und KI-Bewertung.",
  "Everything you need for karaoke parties, audio production, and multiplayer musical experiences \u2014 all in one platform.": "Alles, was du für Karaoke-Partys, Audioproduktion und Multiplayer-Musikerlebnisse brauchst \u2014 alles auf einer Plattform.",
  "Full-featured player management with AI-powered scoring, real-time visuals, and competitive game modes.": "Voll ausgestattetes Spielermanagement mit KI-gestützter Bewertung, Echtzeit-Visuals und kompetitiven Spielmodi.",
  "GO! Pick a song!": "LOS! Wähle einen Song!",
  "Multiplayer Karaoke Experience": "Multiplayer-Karaoke-Erlebnis",
  "Play musical challenges generated from real karaoke songs": "Spiele musikalische Herausforderungen aus echten Karaoke-Songs",
  "Professional Audio Editing": "Professionelle Audiobearbeitung",
  "Ready to get started? Jump into karaoke, create a session, or explore the editor.": "Bereit loszulegen? Starte Karaoke, erstelle eine Sitzung oder erkunde den Editor.",
  "Adjust frequency gain for each note": "Frequenzverstärkung für jede Note anpassen",
  "Separate the uploaded audio into individual stems (vocals, drums, bass, etc.) using AI. You can then preview each stem and choose which one to analyze for pitch detection.": "Trenne das hochgeladene Audio mit KI in einzelne Stems (Gesang, Schlagzeug, Bass usw.). Du kannst dann jeden Stem vorhören und wählen, welcher für die Tonhöhenerkennung analysiert werden soll.",

  // ── Party / Events ──
  "Party": "Party",
  "Parties": "Partys",
  "Party Name": "Partyname",
  "Party (competitive)": "Party (Wettkampf)",
  "Party created successfully!": "Party erfolgreich erstellt!",
  "Create Party": "Party erstellen",
  "Cancel party": "Party absagen",
  "Cancellation reason (optional):": "Absagegrund (optional):",
  "Create Event": "Event erstellen",
  "Edit Event": "Event bearbeiten",
  "Event Date": "Veranstaltungsdatum",
  "Event Photos": "Veranstaltungsfotos",
  "Event name": "Veranstaltungsname",
  "Events Manager": "Veranstaltungsmanager",
  "New Event": "Neues Event",
  "No events found.": "Keine Veranstaltungen gefunden.",
  "Permanently delete this event?": "Diese Veranstaltung endgültig löschen?",
  "Recent events": "Aktuelle Veranstaltungen",
  "Venue": "Veranstaltungsort",
  "Guest Count": "Gästeanzahl",
  "Max Participants": "Max. Teilnehmer",
  "Max people": "Max. Personen",
  "Participant name": "Teilnehmername",
  "Enable waiting list": "Warteliste aktivieren",
  "Fully Reserved": "Vollständig reserviert",
  "Date Proposals": "Terminvorschläge",
  "No date proposals yet.": "Noch keine Terminvorschläge.",
  "Best Dates": "Beste Termine",
  "Schedule": "Zeitplan",
  "No schedule available.": "Kein Zeitplan verfügbar.",
  "Accommodation": "Unterkunft",
  "Catering": "Catering",
  "Food": "Essen",
  "Drinks": "Getränke",
  "Transport": "Transport",
  "Allergens": "Allergene",
  "Gluten-free": "Glutenfrei",
  "Vegan": "Vegan",
  "Vegetarian": "Vegetarisch",

  // ── Polls / Voting ──
  "Create Poll": "Umfrage erstellen",
  "Polls": "Umfragen",
  "No polls yet. Create one to gather votes from participants.": "Noch keine Umfragen. Erstelle eine, um Stimmen der Teilnehmer zu sammeln.",
  "votes": "Stimmen",
  "vote(s)": "Stimme(n)",
  "Remove vote": "Stimme entfernen",
  "Single choice": "Einfachauswahl",
  "Multiple choice": "Mehrfachauswahl",

  // ── Photos ──
  "No photos yet. Be the first to upload!": "Noch keine Fotos. Sei der Erste, der eines hochlädt!",
  "Add photo": "Foto hinzufügen",
  "Edit photo": "Foto bearbeiten",
  "Delete this photo?": "Dieses Foto löschen?",
  "Caption (optional)": "Bildunterschrift (optional)",
  "Add video": "Video hinzufügen",
  "Cover": "Cover",

  // ── Comments / Reviews ──
  "No comments yet.": "Noch keine Kommentare.",
  "No comments yet. Start the conversation!": "Noch keine Kommentare. Starte die Unterhaltung!",
  "No reviews yet.": "Noch keine Bewertungen.",
  "Add a comment\u2026": "Kommentar hinzufügen\u2026",
  "Write a comment...": "Kommentar schreiben...",
  "Write a reply\u2026": "Antwort schreiben\u2026",
  "Write a Review": "Bewertung schreiben",
  "Write a review (optional)\u2026": "Bewertung schreiben (optional)\u2026",
  "Delete this comment?": "Diesen Kommentar löschen?",
  "Post reply": "Antwort senden",
  "Replying to comment": "Antwort auf Kommentar",
  "Contains spoilers": "Enthält Spoiler",
  "Show spoiler": "Spoiler anzeigen",
  "Thank you for your review!": "Vielen Dank für deine Bewertung!",
  "Edit your rating": "Deine Bewertung bearbeiten",
  "No rating": "Keine Bewertung",
  "Rating": "Bewertung",
  "Ratings": "Bewertungen",
  "reviews": "Bewertungen",

  // ── Gift Registry / Wishlists ──
  "New Gift Registry": "Neue Geschenkliste",
  "Shared Gift Registry": "Geteilte Geschenkliste",
  "Gift name": "Geschenkname",
  "Add Gift": "Geschenk hinzufügen",
  "Gift registry not found or link has expired.": "Geschenkliste nicht gefunden oder Link ist abgelaufen.",
  "No gift registries yet.": "Noch keine Geschenklisten.",
  "No gifts in this registry yet.": "Noch keine Geschenke in dieser Liste.",
  "This gift registry is currently closed for contributions.": "Diese Geschenkliste ist derzeit für Beiträge geschlossen.",
  "Create and manage your wishlists. Share them publicly or sync with Steam.": "Erstelle und verwalte deine Wunschlisten. Teile sie öffentlich oder synchronisiere mit Steam.",
  "Create gift lists for events. Share them so guests can contribute to group gifts.": "Erstelle Geschenklisten für Events. Teile sie, damit Gäste zu Gruppengeschenken beitragen können.",
  "Create New Wishlist": "Neue Wunschliste erstellen",
  "Shared Wishlist": "Geteilte Wunschliste",
  "Wishlist name": "Wunschlistenname",
  "Wishlist not found or link has expired.": "Wunschliste nicht gefunden oder Link ist abgelaufen.",
  "No wishlists yet.": "Noch keine Wunschlisten.",
  "This wishlist is empty.": "Diese Wunschliste ist leer.",
  "e.g. Wedding Gift List": "z.B. Hochzeits-Geschenkliste",

  // ── Billing / Payments / Settlement ──
  "Billing": "Abrechnung",
  "Budget": "Budget",
  "Expenses": "Ausgaben",
  "No expenses yet.": "Noch keine Ausgaben.",
  "Payments": "Zahlungen",
  "No payments yet.": "Noch keine Zahlungen.",
  "Settlement": "Abrechnung",
  "Settlement Summary": "Abrechnungsübersicht",
  "No settlement data.": "Keine Abrechnungsdaten.",
  "Split equally": "Gleichmäßig aufteilen",
  "Transfer": "Überweisung",
  "Amount (optional)": "Betrag (optional)",
  "Cash": "Bargeld",
  "Contribute anonymously": "Anonym beitragen",
  "Contributions:": "Beiträge:",

  // ── Organizations ──
  "Organizations": "Organisationen",
  "New Organization": "Neue Organisation",
  "Edit Organization": "Organisation bearbeiten",
  "No organizations yet.": "Noch keine Organisationen.",
  "Organizer ID": "Organisator-ID",
  "Enter organizer ID": "Organisator-ID eingeben",

  // ── Leagues / Sports / Fantasy ──
  "League": "Liga",
  "Leagues": "Ligen",
  "League name": "Liganame",
  "Leagues & Upcoming Events": "Ligen & kommende Veranstaltungen",
  "No leagues yet.": "Noch keine Ligen.",
  "No upcoming events for this league.": "Keine kommenden Veranstaltungen für diese Liga.",
  "Standings": "Tabelle",
  "No standings data.": "Keine Tabellendaten.",
  "Fantasy Leaderboard": "Fantasy-Rangliste",
  "Fantasy Teams": "Fantasy-Teams",
  "No fantasy teams.": "Keine Fantasy-Teams.",
  "Fantasy": "Fantasy",
  "Sport": "Sport",
  "Sports": "Sport",
  "Add Sport Activity": "Sportaktivität hinzufügen",
  "No sport activities yet. Use the lookup above to search TheSportsDB.": "Noch keine Sportaktivitäten. Verwende die Suche oben, um TheSportsDB zu durchsuchen.",
  "Hockey": "Hockey",
  "Volleyball": "Volleyball",
  "Home team": "Heimteam",
  "Away team": "Auswärtsteam",
  "Match Duration": "Spielzeit",
  "Season": "Saison",
  "First air date": "Erstausstrahlung",

  // ── Betting ──
  "Betting": "Wetten",
  "No bets placed yet.": "Noch keine Wetten platziert.",
  "No betting markets for this event.": "Keine Wettmärkte für diese Veranstaltung.",
  "My Bets": "Meine Wetten",
  "My Bet History": "Mein Wettverlauf",
  "Place Bet": "Wette platzieren",
  "Total Wagered": "Gesamt gewettet",
  "Total Won": "Gesamt gewonnen",
  "Markets": "Märkte",
  "Create Market": "Markt erstellen",

  // ── Player / Round / Game ──
  "Player": "Spieler",
  "Players": "Spieler",
  "Player name": "Spielername",
  "Player color": "Spielerfarbe",
  "Player Recordings": "Spieleraufnahmen",
  "Add Player": "Spieler hinzufügen",
  "Add player": "Spieler hinzufügen",
  "Create player": "Spieler erstellen",
  "Click a player to assign": "Klicke auf einen Spieler zum Zuweisen",
  "Error adding profile player": "Fehler beim Hinzufügen des Profilspielers",
  "Error editing profile player": "Fehler beim Bearbeiten des Profilspielers",
  "Set as primary player": "Als Hauptspieler festlegen",
  "Round": "Runde",
  "Rounds": "Runden",
  "Add Round": "Runde hinzufügen",
  "Join round": "Runde beitreten",
  "Delete this round?": "Diese Runde löschen?",
  "No rounds yet": "Noch keine Runden",
  "Rounds to Win": "Runden zum Sieg",
  "Leaderboard": "Rangliste",
  "Game Duration": "Spieldauer",
  "Game Picks": "Spielauswahlen",
  "Game Scoring": "Spielpunkte",
  "Game Speed": "Spielgeschwindigkeit",
  "Game name": "Spielname",
  "Games": "Spiele",
  "Change Game": "Spiel ändern",
  "Choose game type": "Spieltyp auswählen",
  "Start Game": "Spiel starten",
  "Difficulty": "Schwierigkeit",
  "Board Game ID": "Brettspiel-ID",
  "Board Game Scoring": "Brettspiel-Punkte",
  "Board Size": "Spielfeldgröße",
  "Video Game ID": "Videospiel-ID",
  "Video Game Scoring": "Videospiel-Punkte",
  "Video Games": "Videospiele",
  "No board games found": "Keine Brettspiele gefunden",
  "No video games found": "Keine Videospiele gefunden",
  "No game picks yet.": "Noch keine Spielauswahlen.",
  "No song picks yet.": "Noch keine Songauswahlen.",
  "Ranked Games": "Ranglistenspiele",
  "Quick Match": "Schnellspiel",
  "Matchmaking": "Matchmaking",
  "Team": "Team",
  "Teams": "Teams",
  "Team Size": "Teamgröße",
  "Team name": "Teamname",
  "Team Wins!": "Team gewinnt!",
  "Blue Team": "Blaues Team",
  "Red Team": "Rotes Team",
  "Versus": "Versus",
  "Victory!": "Sieg!",
  "Defeat": "Niederlage",
  "Bonus": "Bonus",
  "Points": "Punkte",
  "Reward": "Belohnung",
  "Lobby": "Lobby",
  "Arcade": "Arcade",
  "Random": "Zufall",
  "Free Play": "Freies Spiel",
  "Freestyle": "Freestyle",
  "Solo": "Solo",
  "Solo Challenge": "Solo-Herausforderung",
  "Tutorial": "Tutorial",

  // ── Game genre / mode-specific ──
  "AI Difficulty": "KI-Schwierigkeit",
  "ARAM (1 Lane)": "ARAM (1 Lane)",
  "Arena VS": "Arena VS",
  "Auto Survivors": "Auto-Überlebende",
  "Auto-Fire": "Automatisches Feuer",
  "Battle (VS)": "Kampf (VS)",
  "Blind": "Blind",
  "Breakout": "Breakout",
  "Bullet Density": "Geschossdichte",
  "Bullet Hell": "Bullet Hell",
  "Campaign": "Kampagne",
  "Campaign started!": "Kampagne gestartet!",
  "Campaigns": "Kampagnen",
  "My Campaigns": "Meine Kampagnen",
  "Start Campaign": "Kampagne starten",
  "Failed to start campaign": "Kampagne konnte nicht gestartet werden",
  "Joined campaign!": "Kampagne beigetreten!",
  "No campaigns yet. Start one from the Templates tab!": "Noch keine Kampagnen. Starte eine über den Vorlagen-Tab!",
  "Car Dodge": "Auto ausweichen",
  "Card": "Karte",
  "Career": "Karriere",
  "City Size": "Stadtgröße",
  "Civilization": "Zivilisation",
  "Classic (endgame scoring)": "Klassisch (Endspielwertung)",
  "Classic 5v5": "Klassisch 5v5",
  "Climb": "Klettern",
  "Combat Mode": "Kampfmodus",
  "Conquest (60% systems)": "Eroberung (60% Systeme)",
  "Contract Difficulty": "Vertragsschwierigkeit",
  "Contracts": "Verträge",
  "Deathmatch": "Deathmatch",
  "Desert": "Wüste",
  "Difficulty": "Schwierigkeit",
  "Disaster Frequency": "Katastrophenhäufigkeit",
  "Doom": "Doom",
  "Drag Racing": "Drag Racing",
  "Dungeon Size": "Dungeon-Größe",
  "Dynamic Rules": "Dynamische Regeln",
  "Easy (3 nodes)": "Einfach (3 Knoten)",
  "Elimination": "Eliminierung",
  "Empire RTS": "Empire RTS",
  "Enemy Count": "Gegneranzahl",
  "Escape Room": "Escape Room",
  "Evolution": "Evolution",
  "Farm": "Farm",
  "Fist Only": "Nur Faust",
  "Flat": "Flach",
  "Flatworld Survival": "Flachwelt-Überleben",
  "Flow Speed": "Flussgeschwindigkeit",
  "Free Build": "Freies Bauen",
  "Free Roam": "Freies Erkunden",
  "Free Trade": "Freier Handel",
  "Free for all": "Jeder gegen Jeden",
  "Frenzy": "Frenzy",
  "Galaxy Size": "Galaxiegröße",
  "Grand Prix": "Grand Prix",
  "Growth Rate": "Wachstumsrate",
  "Hard (7 nodes)": "Schwer (7 Knoten)",
  "Higher difficulty = more keys.": "Höhere Schwierigkeit = mehr Tasten.",
  "Hills": "Hügel",
  "Hint Cost": "Hinweiskosten",
  "Hostages": "Geiseln",
  "Hunger": "Hunger",
  "Islands": "Inseln",
  "Kart": "Kart",
  "Kills to Win": "Kills zum Sieg",
  "Kitchen Layout": "Küchenaufteilung",
  "Lane Count": "Spurenanzahl",
  "Level Size": "Levelgröße",
  "Mana": "Mana",
  "Map": "Karte",
  "Map Size": "Kartengröße",
  "Marathon": "Marathon",
  "Max Floors": "Max. Stockwerke",
  "Military": "Militär",
  "Multiball": "Multiball",
  "Online Multiplayer": "Online-Multiplayer",
  "Order Speed": "Bestellgeschwindigkeit",
  "Pipes": "Rohre",
  "Pirates": "Piraten",
  "Pistol": "Pistole",
  "Planets": "Planeten",
  "Pong": "Pong",
  "Power": "Stärke",
  "Power-Ups": "Power-Ups",
  "Puzzle": "Puzzle",
  "Puzzle Matching": "Puzzle-Zuordnung",
  "Race Count": "Rennanzahl",
  "Race Over!": "Rennen vorbei!",
  "Rapid Fire": "Schnellfeuer",
  "Room Count": "Raumanzahl",
  "Round Map": "Rundenkarte",
  "Round robin": "Rundlauf",
  "Sandbox": "Sandbox",
  "Scavenger": "Sammler",
  "Ships": "Schiffe",
  "Shmup": "Shmup",
  "Shotgun": "Schrotflinte",
  "Simon": "Simon",
  "Single Race": "Einzelrennen",
  "Single Shot": "Einzelschuss",
  "Snow": "Schnee",
  "Spawn Rate": "Spawn-Rate",
  "Spread (3 projectiles)": "Streuung (3 Projektile)",
  "Spring": "Frühling",
  "Start Level": "Startlevel",
  "Start Speed": "Startgeschwindigkeit",
  "Starting Age": "Startzeitalter",
  "Starting Budget": "Startbudget",
  "Starting Cash": "Startbargeld",
  "Starting Creatures": "Startkreaturen",
  "Starting Gear": "Startausrüstung",
  "Starting Gold": "Startgold",
  "Starting Life": "Startleben",
  "Starting Money": "Startgeld",
  "Starting Resources": "Startressourcen",
  "Starting Systems": "Startsysteme",
  "Starting Weapon": "Startwaffe",
  "Sumo": "Sumo",
  "Summer": "Sommer",
  "Temperate": "Gemäßigt",
  "Terrain": "Gelände",
  "Tickets per Team": "Tickets pro Team",
  "Time Limit": "Zeitlimit",
  "Tron": "Tron",
  "Turn Mode": "Zugmodus",
  "Turn-Based": "Rundenbasiert",
  "Warzone": "Warzone",
  "Wave Count": "Wellenanzahl",
  "Wild Encounter Rate": "Wildbegegnungsrate",
  "Winter": "Winter",
  "World Size": "Weltgröße",
  "World Theme": "Welt-Thema",
  "Worms Per Team": "Würmer pro Team",
  "Gold per Village": "Gold pro Dorf",
  "Science (all techs)": "Wissenschaft (alle Technologien)",

  // ── Game ages/eras ──
  "Age 1 \u2014 Stone": "Zeitalter 1 \u2014 Stein",
  "Age 2 \u2014 Medieval": "Zeitalter 2 \u2014 Mittelalter",
  "Age 3 \u2014 Industrial": "Zeitalter 3 \u2014 Industrie",

  // ── Game mode types ──
  "Aggro": "Aggro",
  "Alien": "Alien",
  "Balanced": "Ausgewogen",
  "Boss": "Boss",
  "Bronze": "Bronze",
  "Gold": "Gold",
  "Rich": "Reich",
  "Seduction": "Verführung",
  "Silhouette": "Silhouette",
  "Special": "Spezial",
  "Synergy": "Synergie",
  "Settlers": "Siedler",
  "Adventure": "Abenteuer",
  "Buggy": "Buggy",
  "Highlight": "Hervorhebung",

  // ── Co-op modes ──
  "Co-op Build": "Koop-Bauen",
  "Co-op Campaign": "Koop-Kampagne",
  "Co-op City (reach population target together)": "Koop-Stadt (gemeinsam Bevölkerungsziel erreichen)",
  "Co-op Clear": "Koop-Räumung",
  "Co-op Climb": "Koop-Klettern",
  "Co-op Empire (Shared wealth)": "Koop-Imperium (Gemeinsamer Reichtum)",
  "Co-op Escape": "Koop-Flucht",
  "Co-op Heist": "Koop-Raubüberfall",
  "Co-op Kitchen": "Koop-Küche",
  "Co-op Mode": "Koop-Modus",
  "Co-op Network": "Koop-Netzwerk",
  "Co-op Pirates": "Koop-Piraten",
  "Co-op Plumb": "Koop-Klempner",
  "Co-op Quest": "Koop-Quest",
  "Co-op Raid": "Koop-Raid",
  "Co-op Relay": "Koop-Staffel",
  "Co-op Settlement": "Koop-Siedlung",
  "Co-op Solve": "Koop-Lösung",
  "Co-op Target": "Koop-Ziel",
  "Co-op Tournament": "Koop-Turnier",
  "Co-op Tower": "Koop-Turm",
  "Co-op Victory!": "Koop-Sieg!",
  "Co-op vs AI": "Koop gegen KI",
  "Co-op \u2014 Combined Size Target": "Koop \u2014 Gemeinsames Größenziel",
  "Co-op \u2014 Dealers": "Koop \u2014 Händler",
  "Coop Dungeon": "Koop-Dungeon",
  "Story Co-op": "Story-Koop",

  // ── VS modes ──
  "VS Battle": "VS-Kampf",
  "VS Brawl": "VS-Keilerei",
  "VS Conquest": "VS-Eroberung",
  "VS Cops & Robbers": "VS-Räuber und Gendarm",
  "VS Deathmatch": "VS-Deathmatch",
  "VS Hack Race": "VS-Hack-Rennen",
  "VS Height": "VS-Höhe",
  "VS Kitchen": "VS-Küche",
  "VS Market (Sabotage enabled)": "VS-Markt (Sabotage aktiviert)",
  "VS Mayor (compete for highest population)": "VS-Bürgermeister (höchste Bevölkerung gewinnt)",
  "VS Naval": "VS-Seeschlacht",
  "VS Puzzle": "VS-Puzzle",
  "VS Race": "VS-Rennen",
  "VS Rampage": "VS-Randale",
  "VS Rating": "VS-Wertung",
  "VS Score": "VS-Punktzahl",
  "VS Skirmish": "VS-Scharmützel",
  "VS Tycoon": "VS-Tycoon",
  "VS Wasteland": "VS-Ödland",
  "VS \u2014 Biggest Wins": "VS \u2014 Größte Siege",
  "VS \u2014 Distance": "VS \u2014 Distanz",
  "VS \u2014 Wealth": "VS \u2014 Reichtum",
  "Real-Time Battle (VS)": "Echtzeit-Kampf (VS)",

  // ── Game-specific descriptions ──
  "Battle through chapters to earn cards and XP": "Kämpfe dich durch Kapitel, um Karten und XP zu verdienen",
  "Fight a random opponent at your level. Capture cards by defeating them decisively!": "Kämpfe gegen einen zufälligen Gegner auf deinem Level. Erobere Karten durch klare Siege!",
  "Game in progress \u2014 your input is live!": "Spiel läuft \u2014 deine Eingabe ist live!",
  "Hit That Note": "Triff die Note",
  "Hit notes with keys or pad!": "Triff Noten mit Tasten oder Pad!",
  "Memorize and repeat:": "Merken und wiederholen:",
  "No one finished!": "Keiner hat es geschafft!",
  "No skills unlocked yet. Complete campaign rounds to earn skills!": "Noch keine Fähigkeiten freigeschaltet. Schließe Kampagnenrunden ab, um Fähigkeiten zu verdienen!",
  "Press keys or tap pads to start jamming!": "Drücke Tasten oder tippe Pads, um loszujammen!",
  "The dungeon has claimed your party...": "Der Dungeon hat deine Gruppe besiegt...",
  "Too slow!": "Zu langsam!",
  "Wait for the race to start!": "Warte auf den Rennstart!",
  "Adventure complete!": "Abenteuer abgeschlossen!",
  "Survived": "Überlebt",
  "Mission Failed": "Mission gescheitert",
  "Play Again": "Nochmal spielen",
  "New race": "Neues Rennen",
  "Start race": "Rennen starten",
  "Play now": "Jetzt spielen",
  "Start Playing!": "Los geht's!",
  "Start Mic": "Mikrofon starten",
  "Start camera": "Kamera starten",
  "Stop camera": "Kamera stoppen",
  "Try Again": "Erneut versuchen",
  "Unlocked Skills": "Freigeschaltete Fähigkeiten",
  "XP & Levels": "XP & Stufen",
  "XP Earned": "Verdientes XP",
  "Best Streak": "Beste Serie",
  "Cheap (5 coins)": "Günstig (5 Münzen)",
  "Expensive (20 coins)": "Teuer (20 Münzen)",
  "Deck Style": "Deckstil",
  "Deck name...": "Deckname...",

  // ── Game sub-modes ──
  "Idle (Free Play)": "Idle (Freies Spiel)",
  "Tycoon (Free Play)": "Tycoon (Freies Spiel)",
  "Build (Free Play)": "Bauen (Freies Spiel)",
  "Build Time (seconds)": "Bauzeit (Sekunden)",
  "Chill (solo relaxation)": "Chill (Solo-Entspannung)",
  "Classic 5v5": "Klassisch 5v5",
  "Combo (gather + survival)": "Combo (Sammeln + Überleben)",
  "Draft (pick cards first)": "Draft (Karten zuerst wählen)",
  "Gather (collect only, no enemies)": "Sammeln (nur sammeln, keine Gegner)",
  "Immediate (resolve on contact)": "Sofort (bei Kontakt auflösen)",
  "Overdub (play background)": "Overdub (Hintergrund abspielen)",
  "Publish (make public)": "Veröffentlichen (öffentlich machen)",
  "Skirmish (FFA)": "Scharmützel (FFA)",
  "Timed \u2014 High Score": "Zeitlimit \u2014 Highscore",
  "Best of Five": "Best of Five",
  "All Must Pass": "Alle müssen bestehen",
  "Any One Pass": "Einer muss bestehen",
  "At set interval": "In festem Intervall",
  "On every change": "Bei jeder Änderung",
  "First come": "Wer zuerst kommt",
  "Host only": "Nur Gastgeber",
  "Match all / any of these rules": "Alle / beliebige dieser Regeln erfüllen",
  "Police Aggression": "Polizeiaggression",

  // ── Pose / Camera / AI ──
  "Pose Cam Game": "Posen-Kameraspiel",
  "Pose Detection  Image": "Posenerkennung  Bild",
  "Pose Tracking  Video": "Posenverfolgung  Video",
  "Save a target pose, then match it with your body in front of the camera. The more accurate  the higher the score!": "Speichere eine Zielpose, dann stimme sie mit deinem Körper vor der Kamera ab. Je genauer, desto höher die Punktzahl!",
  "Save current pose": "Aktuelle Pose speichern",
  "Target pose": "Zielpose",
  "Load a single image and detect 2D poses using an AI engine.": "Lade ein Bild und erkenne 2D-Posen mit einer KI-Engine.",
  "Load a video and track body movements frame by frame.": "Lade ein Video und verfolge Körperbewegungen Bild für Bild.",
  "Transform a 2D sequence into a 3D pose estimation.": "Transformiere eine 2D-Sequenz in eine 3D-Posenschätzung.",
  "Use camera and AI for body position recognition. Match poses, track movement, or analyze 3D video.": "Nutze Kamera und KI zur Körperpositionserkennung. Posen abgleichen, Bewegungen verfolgen oder 3D-Video analysieren.",
  "Classification Results": "Klassifikationsergebnisse",
  "Segmentation Heatmap": "Segmentierungs-Heatmap",
  "Live camera": "Live-Kamera",
  "Image Question": "Bildfrage",
  "Image Region Selection": "Bildbereichsauswahl",
  "Image Selection": "Bildauswahl",
  "Select an image first.": "Wähle zuerst ein Bild aus.",
  "Select a video first.": "Wähle zuerst ein Video aus.",

  // ── DMX / Lighting ──
  "DMX Editor": "DMX-Editor",
  "Control DMX lighting via serial port": "DMX-Beleuchtung über serielle Schnittstelle steuern",
  "Manage DMX devices, port configuration and channels.": "DMX-Geräte, Port-Konfiguration und Kanäle verwalten.",
  "Close port": "Port schließen",
  "Open port": "Port öffnen",
  "Turn off channel (set OFF range)": "Kanal ausschalten (OFF-Bereich setzen)",
  "Device": "Gerät",
  "Enter custom device name": "Eigenen Gerätenamen eingeben",
  "Import Fixture": "Fixture importieren",

  // ── Stem Separation ──
  "Separate Tracks": "Tracks trennen",
  "Separate Tracks (Demucs)": "Tracks trennen (Demucs)",
  "Download ZIP with stems": "ZIP mit Stems herunterladen",
  "Separating\u2026": "Wird getrennt\u2026",
  "Separation Error": "Trennungsfehler",
  "Separation returned no audio tracks.": "Trennung ergab keine Audiotracks.",
  "Processing with Demucs \u2014 this can take 1-3 minutes depending on file length\u2026": "Verarbeitung mit Demucs \u2014 dies kann je nach Dateilänge 1-3 Minuten dauern\u2026",
  "Stems:": "Stems:",
  "Use Original File": "Originaldatei verwenden",
  "Use Selected Stem for Analysis": "Ausgewählten Stem für Analyse verwenden",
  "Select track to analyze:": "Track zur Analyse auswählen:",
  "Sources found for tracks": "Quellen für Tracks gefunden",

  // ── Playlists ──
  "My Playlists": "Meine Playlists",
  "Online Playlists": "Online-Playlists",
  "No online playlists": "Keine Online-Playlists",
  "No playlists yet": "Noch keine Playlists",
  "No playlists. Add the first one ": "Keine Playlists. Füge die erste hinzu ",
  "Create playlist": "Playlist erstellen",
  "Delete playlist": "Playlist löschen",
  "Playlist name": "Playlistname",
  "Playlist name...": "Playlistname...",
  "Save to My Playlists": "In meine Playlists speichern",
  "Select a playlist first": "Wähle zuerst eine Playlist",
  "Select a playlist first.": "Wähle zuerst eine Playlist aus.",
  "Search and add to playlist...": "Suchen und zur Playlist hinzufügen...",
  "Successfully exported playlists!": "Playlists erfolgreich exportiert!",
  "Successfully imported playlists!": "Playlists erfolgreich importiert!",
  "This import might overwrite existing playlists. Continue?": "Dieser Import könnte bestehende Playlists überschreiben. Fortfahren?",
  "Tracks matching these rules will automatically be included in the playlist.": "Tracks, die diesen Regeln entsprechen, werden automatisch in die Playlist aufgenommen.",
  "Unsupported file format. Use .json, .m3u, .m3u8 or .csv.": "Nicht unterstütztes Dateiformat. Verwende .json, .m3u, .m3u8 oder .csv.",
  "Export to Spotify": "Zu Spotify exportieren",
  "Export to Tidal": "Zu Tidal exportieren",
  "Export to YouTube": "Zu YouTube exportieren",
  "Import from Collection ID": "Aus Sammlungs-ID importieren",
  "Import from Playlist ID": "Aus Playlist-ID importieren",

  // ── Search ──
  "Search...": "Suche...",
  "Searching...": "Wird gesucht...",
  "Search\u2026": "Suche\u2026",
  "Search events\u2026": "Veranstaltungen suchen\u2026",
  "Search artist / title...": "Künstler / Titel suchen...",
  "Search library": "Bibliothek durchsuchen",
  "Search library (Audio)...": "Bibliothek durchsuchen (Audio)...",
  "Search external...": "Extern suchen...",
  "Search users (min 3 chars)": "Benutzer suchen (min. 3 Zeichen)",
  "Search OpenLibrary / Google Books to auto-fill...": "OpenLibrary / Google Books durchsuchen...",
  "Search TMDb to auto-fill...": "TMDb durchsuchen...",
  "Search TheSportsDB to auto-fill...": "TheSportsDB durchsuchen...",
  "Search your TV shows...": "Deine Serien durchsuchen...",
  "Search your books...": "Deine Bücher durchsuchen...",
  "Search your movies...": "Deine Filme durchsuchen...",
  "Search your sport activities...": "Deine Sportaktivitäten durchsuchen...",
  "No search results": "Keine Suchergebnisse",
  "No results": "Keine Ergebnisse",
  "No results.": "Keine Ergebnisse.",
  "No results for this song.": "Keine Ergebnisse für diesen Song.",
  "No matches": "Keine Treffer",
  "Full search (Enter does not add, full list below)": "Vollsuche (Enter fügt nicht hinzu, vollständige Liste unten)",
  "Type to search...": "Suche eingeben...",

  // ── Library / Catalog ──
  "Library": "Bibliothek",
  "Library Catalog": "Bibliothekskatalog",
  "Books": "Bücher",
  "Movies": "Filme",
  "TV Shows": "Serien",
  "Add Album": "Album hinzufügen",
  "Add Artist": "Künstler hinzufügen",
  "Add Book": "Buch hinzufügen",
  "Add Movie": "Film hinzufügen",
  "Add TV Show": "Serie hinzufügen",
  "No books yet. Use the lookup above to import from external sources.": "Noch keine Bücher. Verwende die Suche oben, um aus externen Quellen zu importieren.",
  "No movies yet. Use the lookup above to import from TMDb.": "Noch keine Filme. Verwende die Suche oben, um von TMDb zu importieren.",
  "No TV shows yet. Use the lookup above to import from TMDb.": "Noch keine Serien. Verwende die Suche oben, um von TMDb zu importieren.",
  "Manage songs, albums, artists, audio files, and folder scan/import.": "Songs, Alben, Künstler, Audiodateien und Ordner-Scan/Import verwalten.",
  "Manage available UI skins used in the theme picker": "Verfügbare UI-Skins im Theme-Picker verwalten",
  "Manage your YouTube channel subscriptions.": "Verwalte deine YouTube-Kanalabonnements.",
  "No subscriptions found. Make sure your YouTube account is linked.": "Keine Abonnements gefunden. Stelle sicher, dass dein YouTube-Konto verknüpft ist.",
  "Director": "Regisseur",
  "Release date": "Veröffentlichungsdatum",
  "Poster (optional)": "Poster (optional)",
  "Poster URL": "Poster-URL",
  "Genre": "Genre",
  "Linked Artist": "Verknüpfter Künstler",
  "Version (optional)": "Version (optional)",
  "Version History": "Versionsverlauf",
  "No versions available.": "Keine Versionen verfügbar.",
  "Select a version to preview": "Wähle eine Version zur Vorschau",
  "You do not have permission to revert versions.": "Du hast keine Berechtigung, Versionen zurückzusetzen.",
  "You do not have permission to view version history.": "Du hast keine Berechtigung, den Versionsverlauf anzuzeigen.",
  "Reason for reverting": "Grund für die Rücksetzung",

  // ── File / Folder / Import/Export ──
  "File": "Datei",
  "File information": "Dateiinformationen",
  "Folder Path": "Ordnerpfad",
  "Selected file": "Ausgewählte Datei",
  "Select a file first.": "Wähle zuerst eine Datei aus.",
  "No files.": "Keine Dateien.",
  "Scan & Import": "Scannen & Importieren",
  "Scan & Import Folder": "Ordner scannen & importieren",
  "Scan a server folder for audio files and auto-import them into the library catalog.": "Scanne einen Server-Ordner nach Audiodateien und importiere sie automatisch in den Bibliothekskatalog.",
  "Scan and import completed!": "Scannen und Import abgeschlossen!",
  "Scan failed. Check the folder path.": "Scan fehlgeschlagen. Überprüfe den Ordnerpfad.",
  "Merge Folders": "Ordner zusammenführen",
  "Merge Tags": "Tags zusammenführen",
  "Export All": "Alles exportieren",
  "Export Collection": "Sammlung exportieren",
  "Export Selected": "Ausgewählte exportieren",
  "Export failed": "Export fehlgeschlagen",
  "Export failed.": "Export fehlgeschlagen.",
  "Export format": "Exportformat",
  "Import Collection": "Sammlung importieren",
  "Import Options": "Importoptionen",
  "Import to editor": "In Editor importieren",
  "Imports generated MIDI notes into current project layers": "Importiert generierte MIDI-Noten in aktuelle Projektebenen",
  "Overwrite Existing": "Vorhandenes überschreiben",
  "This will add games from the file to your collection. Duplicates might occur. Continue?": "Dies fügt Spiele aus der Datei zu deiner Sammlung hinzu. Duplikate können auftreten. Fortfahren?",
  "With metadata": "Mit Metadaten",
  "Without metadata": "Ohne Metadaten",
  "Without template": "Ohne Vorlage",
  "MIME Type": "MIME-Typ",

  // ── Project / Editor ──
  "Pixel Editor": "Pixel-Editor",
  "Vector Editor": "Vektor-Editor",
  "Verse Editor v0.01": "Verse-Editor v0.01",
  "Open in Editor": "Im Editor öffnen",
  "New Project": "Neues Projekt",
  "Project List": "Projektliste",
  "Projects List": "Projektliste",
  "Project name": "Projektname",
  "Project auto-save": "Projekt-Auto-Speicherung",
  "Project change history": "Projekt-Änderungsverlauf",
  "Add Project": "Projekt hinzufügen",
  "Auto-save frequency (seconds)": "Auto-Speicher-Intervall (Sekunden)",
  "Auto-save mode": "Auto-Speicher-Modus",
  "Auto-save works locally (localStorage/browser). Manual save (PUT) always overwrites the project on the server.": "Auto-Speicherung funktioniert lokal (localStorage/Browser). Manuelles Speichern (PUT) überschreibt immer das Projekt auf dem Server.",
  "Save (to backend)": "Speichern (im Backend)",
  "Save Changes": "Änderungen speichern",
  "Save Current": "Aktuelle speichern",
  "Save Full Backup": "Vollständiges Backup speichern",
  "Save Preset": "Vorlage speichern",
  "Save Run": "Lauf speichern",
  "Save current params & score to history": "Aktuelle Parameter & Punktzahl in Verlauf speichern",
  "Save error: ": "Speicherfehler: ",
  "Save layer": "Ebene speichern",
  "Saved locally (no mic record on backend)": "Lokal gespeichert (keine Mic-Aufnahme im Backend)",
  "Saved to profile (backend)": "Im Profil gespeichert (Backend)",
  "Saving...": "Wird gespeichert...",
  "Undo last change (Ctrl+Z)": "Letzte Änderung rückgängig machen (Strg+Z)",
  "Redo change (Ctrl+Y or Ctrl+Shift+Z)": "Änderung wiederherstellen (Strg+Y oder Strg+Umschalt+Z)",
  "Undo/Redo works on the entire project (all editor changes). After each change Redo is cleared.": "Rückgängig/Wiederherstellen wirkt auf das gesamte Projekt (alle Editor-Änderungen). Nach jeder Änderung wird Wiederherstellen gelöscht.",
  "Restore Backup": "Backup wiederherstellen",
  "Add Layer": "Ebene hinzufügen",
  "Layer name": "Ebenenname",
  "Audio Layer": "Audio-Ebene",
  "Add AudioClip": "AudioClip hinzufügen",
  "Add New AudioClip": "Neuen AudioClip hinzufügen",
  "Preset": "Vorlage",
  "Presets": "Vorlagen",
  "Preset Sweep": "Vorlage-Sweep",
  "Preset name...": "Vorlagenname...",
  "Load Preset": "Vorlage laden",
  "Delete preset...": "Vorlage löschen...",
  "Outline": "Umriss",
  "Live Preview": "Live-Vorschau",
  "Preview JSON": "JSON-Vorschau",

  // Calibration ──
  "Calibrate": "Kalibrieren",
  "Calibration error: ": "Kalibrierungsfehler: ",
  "Latency Calibrator  microphone": "Latenz-Kalibrator  Mikrofon",
  "Measured offset": "Gemessener Offset",
  "Auto-find best offset": "Besten Offset automatisch finden",
  "Sweep -500..+500 ms to find offset that maximises scoring total": "Sweep -500..+500 ms, um den Offset mit maximaler Gesamtpunktzahl zu finden",
  "Playing test tone and recording...": "Testton wird abgespielt und aufgenommen...",

  // ── Tuning ──
  "Tuning Harness": "Tuning-Testumgebung",
  "Tuning Run History": "Tuning-Laufverlauf",
  "Analyzing track:": "Track wird analysiert:",
  "Librosa (PYIN)": "Librosa (PYIN)",
  "Librosa pYIN (server)": "Librosa pYIN (Server)",
  "Per-Note Detail": "Detail pro Note",

  // ── Misc features & errors ──
  "Accuracy": "Genauigkeit",
  "Action": "Aktion",
  "Active filters": "Aktive Filter",
  "Activity": "Aktivität",
  "All Actions": "Alle Aktionen",
  "All Countries": "Alle Länder",
  "All fields are required!": "Alle Felder sind erforderlich!",
  "All sources": "Alle Quellen",
  "Assignments": "Zuweisungen",
  "At": "Um",
  "Attractions": "Attraktionen",
  "Auction House": "Auktionshaus",
  "AudioVerse Features": "AudioVerse-Funktionen",
  "Auto assign": "Automatisch zuweisen",
  "Auto-play": "Automatische Wiedergabe",
  "Average": "Durchschnitt",
  "Avg / Day": "Durchschn. / Tag",
  "Avg Response": "Durchschn. Antwort",
  "Best": "Beste",
  "Both": "Beide",
  "Bots": "Bots",
  "Browse by": "Durchsuchen nach",
  "Browse free internet radio stations from around the world.": "Durchsuche kostenlose Internetradiosender aus der ganzen Welt.",
  "Browser requires a click to unlock": "Browser erfordert einen Klick zum Entsperren",
  "Bulk Invite": "Masseneinladung",
  "By Genre": "Nach Genre",
  "By Year": "Nach Jahr",
  "Chat": "Chat",
  "City": "Stadt",
  "Clear All": "Alles leeren",
  "Clear punch": "Punch zurücksetzen",
  "Clear selection": "Auswahl aufheben",
  "Click any element to edit its color": "Klicke auf ein Element, um seine Farbe zu bearbeiten",
  "Click to edit score": "Klicken, um Punktzahl zu bearbeiten",
  "Click to remove": "Klicken zum Entfernen",
  "Code:": "Code:",
  "Collage name": "Collagenname",
  "Collages": "Collagen",
  "No collages yet.": "Noch keine Collagen.",
  "Connection lost \u2014 retries exhausted": "Verbindung verloren \u2014 Wiederholungsversuche erschöpft",
  "Contacts": "Kontakte",
  "Control": "Steuerung",
  "Controller": "Controller",
  "Controls": "Steuerung",
  "Could not load karaoke projects. The server may be unavailable.": "Karaoke-Projekte konnten nicht geladen werden. Der Server ist möglicherweise nicht erreichbar.",
  "Creating...": "Wird erstellt...",
  "Changing...": "Wird geändert...",
  "Dance Classification": "Tanzklassifizierung",
  "Dance Matches": "Tanz-Treffer",
  "Dance Styles Reference": "Tanzstil-Referenz",
  "Debug": "Debug",
  "Delete section": "Abschnitt löschen",
  "Description (optional)": "Beschreibung (optional)",
  "Display Settings": "Anzeigeeinstellungen",
  "End": "Ende",
  "Engine": "Engine",
  "Enter a song ID to look up dance information.": "Gib eine Song-ID ein, um Tanzinformationen nachzuschlagen.",
  "Enter artist": "Künstler eingeben",
  "Enter description": "Beschreibung eingeben",
  "Enter party name": "Partynamen eingeben",
  "Enter text...": "Text eingeben...",
  "Enter title": "Titel eingeben",
  "Exponential": "Exponentiell",
  "Few": "Wenig",
  "Font color": "Schriftfarbe",
  "Font size": "Schriftgröße",
  "Free": "Frei",
  "Gamepad Controls": "Gamepad-Steuerung",
  "Gamepads": "Gamepads",
  "Hello World!": "Hallo Welt!",
  "Hide Ranking": "Rangliste ausblenden",
  "Hide Results": "Ergebnisse ausblenden",
  "Show Ranking": "Rangliste anzeigen",
  "Show Results": "Ergebnisse anzeigen",
  "Hub": "Hub",
  "In Progress": "In Bearbeitung",
  "Invite Templates": "Einladungsvorlagen",
  "Item name": "Artikelname",
  "Keyboard Controls": "Tastatursteuerung",
  "Last detection (live) JSON": "Letzte Erkennung (Live) JSON",
  "Last modified": "Zuletzt geändert",
  "Last sync": "Letzte Synchronisierung",
  "Linear": "Linear",
  "Loading BGG suggestions...": "BGG-Vorschläge werden geladen...",
  "Loading analytics...": "Analyse wird geladen...",
  "Loading player data\u2026": "Spielerdaten werden geladen\u2026",
  "Loading user info...": "Benutzerinfo wird geladen...",
  "Location Name": "Ortsname",
  "Location Type": "Ortstyp",
  "Log in to see your activity.": "Melde dich an, um deine Aktivität zu sehen.",
  "Log in to see your wallet.": "Melde dich an, um dein Wallet zu sehen.",
  "Logo URL": "Logo-URL",
  "Lower": "Unterer",
  "Upper": "Oberer",
  "Main navigation": "Hauptnavigation",
  "Many": "Viele",
  "Mark all as read": "Alle als gelesen markieren",
  "Math Problem": "Mathe-Aufgabe",
  "Max": "Max",
  "Max (min)": "Max (Min.)",
  "Max tracks:": "Max. Tracks:",
  "Memo": "Memo",
  "Message (optional)": "Nachricht (optional)",
  "Metadata parse warning:": "Metadaten-Parswarnung:",
  "Min": "Min",
  "Min (min)": "Min (Min.)",
  "Monitor": "Monitor",
  "Move down": "Nach unten",
  "Move left": "Nach links",
  "Move right": "Nach rechts",
  "Move up": "Nach oben",
  "My History": "Mein Verlauf",
  "My Lists": "Meine Listen",
  "My Wallet": "Mein Wallet",
  "Next 7 days": "Nächste 7 Tage",
  "Next week": "Nächste Woche",
  "Next \u2192": "Weiter \u2192",
  "No BGG suggestions": "Keine BGG-Vorschläge",
  "No activity data for this period.": "Keine Aktivitätsdaten für diesen Zeitraum.",
  "No analysis data available.": "Keine Analysedaten verfügbar.",
  "No attractions suggested yet.": "Noch keine Attraktionen vorgeschlagen.",
  "No gamepad detected. Connect an Xbox controller.": "Kein Gamepad erkannt. Verbinde einen Xbox-Controller.",
  "No menu items yet.": "Noch keine Menüeinträge.",
  "No microphones detected": "Keine Mikrofone erkannt",
  "No notifications": "Keine Benachrichtigungen",
  "No parts yet": "Noch keine Teile",
  "No permission": "Keine Berechtigung",
  "No portfolio items yet.": "Noch keine Portfolio-Einträge.",
  "No price list items yet.": "Noch keine Preislisten-Einträge.",
  "No progress data yet. Start singing!": "Noch keine Fortschrittsdaten. Fang an zu singen!",
  "No radio station selected.": "Kein Radiosender ausgewählt.",
  "No ranking data yet.": "Noch keine Ranglistendaten.",
  "No recording": "Keine Aufnahme",
  "No saved locations": "Keine gespeicherten Orte",
  "No signal detected  try louder or check microphone": "Kein Signal erkannt – versuche lauter oder prüfe das Mikrofon",
  "No tags yet.": "Noch keine Tags.",
  "No templates available.": "Keine Vorlagen verfügbar.",
  "No text": "Kein Text",
  "No tracks found in file.": "Keine Tracks in der Datei gefunden.",
  "Notifications": "Benachrichtigungen",
  "Objective": "Ziel",
  "Other": "Sonstiges",
  "Overall": "Gesamt",
  "Access": "Zugriff",
  "Add (Write)": "Hinzufügen (Schreiben)",
  "Add Attraction": "Attraktion hinzufügen",
  "Add part": "Teil hinzufügen",
  "Add from list": "Aus Liste hinzufügen",
  "Add a note (optional)\u2026": "Notiz hinzufügen (optional)\u2026",
  "Add a tag\u2026": "Tag hinzufügen\u2026",
  "Apply configuration": "Konfiguration anwenden",
  "Are you sure?": "Bist du sicher?",
  "Activate audio": "Audio aktivieren",
  "Accepted JSON for sequence.": "JSON für Sequenz akzeptiert.",
  "Accepted: JPEG/PNG.": "Akzeptiert: JPEG/PNG.",
  "Accepted: MP4.": "Akzeptiert: MP4.",

  // ── Page / Navigation ──
  "Page not found": "Seite nicht gefunden",
  "Page size": "Seitengröße",
  "Pad / Gamepad": "Pad / Gamepad",
  "Pad Mode  Activate audio": "Pad-Modus  Audio aktivieren",
  "Pads": "Pads",

  // ── Misc categories ──
  "Wallet": "Wallet",
  "Portfolio": "Portfolio",
  "News Feeds": "Nachrichten-Feeds",
  "Feeds": "Feeds",
  "Wiki": "Wiki",
  "Wiki / Docs": "Wiki / Doku",
  "Wiki \u2014 Manage pages": "Wiki \u2014 Seiten verwalten",
  "Tags": "Tags",
  "Contacts": "Kontakte",
  "Honest Living": "Ehrliches Leben",
  "Radio": "Radio",
  "Go to Radio Station": "Zum Radiosender gehen",
  "Go to homepage": "Zur Startseite",
  "Website": "Webseite",
  "Real-Time": "Echtzeit",
  "Streaming": "Streaming",
  "Remote": "Fernsteuerung",
  "Social": "Sozial",
  "Speech Synth": "Sprachsynthese",
  "Studio": "Studio",
  "Progress": "Fortschritt",
  "Progression": "Steigerung",
  "Pipeline": "Pipeline",
  "Summary": "Zusammenfassung",
  "Results": "Ergebnisse",
  "Processing": "Verarbeitung",
  "Processing...": "Wird verarbeitet...",
  "Posting...": "Wird gesendet...",
  "Uploading...": "Wird hochgeladen...",
  "Updating\u2026": "Wird aktualisiert\u2026",
  "Reverting": "Wird zurückgesetzt",
  "Unavailable": "Nicht verfügbar",
  "Cap shape": "Kappenform",
  "Texture": "Textur",
  "Texture scale": "Texturskalierung",
  "Text shadow": "Textschatten",
  "Pattern color": "Musterfarbe",
  "Pattern only (flat, no 3D)": "Nur Muster (flach, kein 3D)",
  "Transparency (glass)": "Transparenz (Glas)",
  "Seek position": "Suchposition",
  "Response JSON": "Antwort-JSON",
  "Reverse String": "Zeichenkette umkehren",
  "The quick brown fox jumps over the lazy dog": "Franz jagt im komplett verwahrlosten Taxi quer durch Bayern",
  "Slug": "Slug",
  "Repeats": "Wiederholungen",
  "Swing": "Swing",
  "Toggle AND/OR": "UND/ODER umschalten",
  "Trace Speed": "Spurgeschwindigkeit",
  "Track costs per option": "Kosten pro Option verfolgen",

  // ── Invite / Join ──
  "Join and play": "Beitreten und spielen",
  "Failed to join": "Beitritt fehlgeschlagen",
  "Failed to accept the invite. Please try again.": "Einladung konnte nicht angenommen werden. Bitte versuche es erneut.",
  "This invite link is invalid or has expired.": "Dieser Einladungslink ist ungültig oder abgelaufen.",
  "Send Bulk Invites": "Masseneinladungen senden",
  "Send Inquiry": "Anfrage senden",
  "Email addresses (comma or newline separated)": "E-Mail-Adressen (Komma- oder zeilengetrennt)",
  "Email body (HTML)": "E-Mail-Text (HTML)",
  "Email subject": "E-Mail-Betreff",
  "Emails (comma separated)": "E-Mails (kommagetrennt)",
  "You have been added as a guest to {{station}}.": "Du wurdest als Gast zu {{station}} hinzugefügt.",
  "You have been invited to join as a guest DJ.": "Du wurdest eingeladen, als Gast-DJ mitzumachen.",
  "Your inquiry has been sent! The vendor will contact you soon.": "Deine Anfrage wurde gesendet! Der Anbieter wird sich bald bei dir melden.",
  "Remove Signup": "Anmeldung entfernen",

  // ── Mic / Audio ──
  "Requesting microphone... click allow if prompted": "Mikrofon wird angefragt... klicke auf Erlauben, wenn aufgefordert",
  "No microphones detected": "Keine Mikrofone erkannt",
  "microphone and audio playback.": "Mikrofon und Audiowiedergabe.",
  "YouTube video player": "YouTube-Videoplayer",

  // ── Paste / multiline ──
  "Paste lines in format:\nArtist - Title (Version)\nArtist  Title [Remastered 2011]\nOR: Artist;Title;Version": "Zeilen im Format einfügen:\nKünstler - Titel (Version)\nKünstler  Titel [Remastered 2011]\nODER: Künstler;Titel;Version",
  "Paste multiple items at once": "Mehrere Einträge gleichzeitig einfügen",

  // ── Notifications ──
  "Settings saved!": "Einstellungen gespeichert!",
  "Test E-mail": "Test-E-Mail",
  "Test SMS": "Test-SMS",
  "Test the live singing score endpoint to verify accuracy.": "Teste den Live-Gesangspunktzahl-Endpunkt zur Genauigkeitsprüfung.",
  "Test the live singing score endpoint. Start the microphone, sing, and see your score in real time. This helps verify the effectiveness of the scoring algorithm.": "Teste den Live-Gesangspunktzahl-Endpunkt. Starte das Mikrofon, singe und sieh deine Punktzahl in Echtzeit. Dies hilft, die Effektivität des Bewertungsalgorithmus zu überprüfen.",

  // ── "This" messages ──
  "This weekend": "Dieses Wochenende",
  "Tips": "Tipps",

  // ── Months ──
  "Jan": "Jan",
  "Feb": "Feb",
  "Apr": "Apr",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Aug",
  "Sep": "Sep",
  "Nov": "Nov",

  // ── Misc lowercase ──
  "active": "aktiv",
  "bars": "Takte",
  "cards": "Karten",
  "clear": "leeren",
  "contributors": "Beitragende",
  "days": "Tage",
  "edited": "bearbeitet",
  "events": "Veranstaltungen",
  "items": "Einträge",
  "just now": "gerade eben",
  "none": "keine",
  "picks!": "Auswahlen!",
  "random": "zufällig",
  "remember to call URL.revokeObjectURL after download": "denke daran URL.revokeObjectURL nach dem Download aufzurufen",
  "reviews": "Bewertungen",
  "rounds": "Runden",
  "rounds completed": "Runden abgeschlossen",
  "seasons": "Staffeln",
  "sec": "Sek.",
  "signup(s)": "Anmeldung(en)",
  "songs": "Songs",
  "stations found": "Sender gefunden",
  "streak": "Serie",
  "tracks": "Tracks",
  "vendors": "Anbieter",
  "e.g. rock, jazz, news...": "z.B. Rock, Jazz, Nachrichten...",

  // ── Misc "No ..." ──
  "No recording": "Keine Aufnahme",

  // ── Steam / Gamepad ──
  "Steam ID (e.g. 76561198...)": "Steam-ID (z.B. 76561198...)",
  "Sync Now": "Jetzt synchronisieren",
  "Registered user gamepads": "Registrierte Benutzer-Gamepads",
  "Xbox Gamepad Controller": "Xbox Gamepad-Controller",
  "No gamepad detected. Connect an Xbox controller.": "Kein Gamepad erkannt. Verbinde einen Xbox-Controller.",

  // ── View / Visibility ──
  "View Product": "Produkt ansehen",
  "Visibility": "Sichtbarkeit",
  "Suggest something for the group!": "Schlage der Gruppe etwas vor!",
  "Please log in to see your progress.": "Bitte melde dich an, um deinen Fortschritt zu sehen.",

  // ── Reconnect ──
  "Reconnect \u2014 game will resume automatically. Click to dismiss.": "Wiederverbindung \u2014 Spiel wird automatisch fortgesetzt. Klicken zum Schließen.",

  // ── Polish values → German ──
  "Anuluj": "Abbrechen",
  "Adresat": "Empfänger",
  "Atrakcja nie znaleziona.": "Attraktion nicht gefunden.",
  "Auto przypisanie": "Automatische Zuweisung",
  "Bez mikrofonu": "Ohne Mikrofon",
  "Brak imprez": "Keine Veranstaltungen",
  "Brak imprez w podanym promieniu.": "Keine Veranstaltungen im angegebenen Umkreis.",
  "Brak opisu": "Keine Beschreibung",
  "Czas": "Zeit",
  "Czas trwania (min)": "Dauer (Min.)",
  "Dane Google Places": "Google-Places-Daten",
  "Dodaj opis atrakcji...": "Beschreibung der Attraktion hinzufügen...",
  "Dodatkowy komentarz (opcjonalnie)...": "Zusätzlicher Kommentar (optional)...",
  "Dystans": "Entfernung",
  "Edytuj film": "Film bearbeiten",
  "Filmy": "Filme",
  "Gatunek: Wszystkie": "Genre: Alle",
  "Godziny": "Stunden",
  "Gra planszowa": "Brettspiel",
  "Gra wideo": "Videospiel",
  "Gracz": "Spieler",
  "Graj": "Spielen",
  "Ikona": "Symbol",
  "Informacje": "Informationen",
  "Inna atrakcja": "Andere Attraktion",
  "Komentarz moderatora...": "Moderatorkommentar...",
  "Kroki nawigacji": "Navigationsschritte",
  "Lokalizacje i mapa": "Orte und Karte",
  "Mikrofon": "Mikrofon",
  "Mikrofony": "Mikrofone",
  "Moja lokalizacja": "Mein Standort",
  "Nazwa sesji": "Sitzungsname",
  "Nowa kolekcja": "Neue Sammlung",
  "Np. Karaoke - Runda 1": "z.B. Karaoke - Runde 1",
  "Numer telefonu": "Telefonnummer",
  "Odrzucona propozycja": "Abgelehnter Vorschlag",
  "Odrzucone": "Abgelehnt",
  "Odrzucone propozycje": "Abgelehnte Vorschläge",
  "Odwrotne geokodowanie": "Umgekehrte Geokodierung",
  "Ogranicz do playlisty eventu": "Auf Event-Playlist beschränken",
  "Opis": "Beschreibung",
  "Parkiet": "Tanzfläche",
  "Pady": "Pads",
  "Podpis (opcjonalnie)": "Signatur (optional)",
  "Powiadomienia": "Benachrichtigungen",
  "Powiadomienia \u2014 test": "Benachrichtigungen \u2014 Test",
  "Propozycja": "Vorschlag",
  "Propozycja atrakcji": "Attraktionsvorschlag",
  "Propozycje": "Vorschläge",
  "Prywatny": "Privat",
  "Przypisania": "Zuweisungen",
  "Publiczny": "Öffentlich",
  "Punkt A (start)": "Punkt A (Start)",
  "Punkt B (cel)": "Punkt B (Ziel)",
  "Restauracja, klub, adres\u2026": "Restaurant, Club, Adresse\u2026",
  "Rok: Wszystkie": "Jahr: Alle",
  "Rundy": "Runden",
  "Sesja": "Sitzung",
  "Sesja aktywna": "Aktive Sitzung",
  "Stacjonarna": "Stationär",
  "Strefa czasowa": "Zeitzone",
  "Szukaj": "Suche",
  "Szukaj...": "Suche...",
  "Temat": "Thema",
  "Test SMS (SMSAPI) i e-mail": "Test SMS (SMSAPI) und E-Mail",
  "Trasa A \u2192 B": "Route A \u2192 B",
  "Tryb sesji": "Sitzungsmodus",
  "Wg gatunku": "Nach Genre",
  "Wg roku": "Nach Jahr",
  "Wirtualna": "Virtuell",
  "Wszystkie": "Alle",
  "Wybierz": "Auswählen",
  "Wybierz gracza...": "Spieler auswählen...",
  "Wyniki": "Ergebnisse",
  "Wyszukaj miejsce": "Ort suchen",
  "Zapisano \u2713": "Gespeichert \u2713",
  "Zastosuj": "Anwenden",
  "Zatwierdzone": "Genehmigt",
  "Zmniejsz": "Verkleinern",
  "graczy": "Spieler",
  "lub": "oder",
  "piosenek": "Songs",
  "zmiana trybu": "Moduswechsel",

  // ── Emoji-prefixed strings ──
  "\u2694\uFE0F Campaign": "\u2694\uFE0F Kampagne",
  "\u2694\uFE0F Fight!": "\u2694\uFE0F Kampf!",
  "\u2B1C Empty bar (unsung)": "\u2B1C Leerer Balken (ungesungen)",
  "\u2B50 Gold empty bar (unsung)": "\u2B50 Gold-Leerer Balken (ungesungen)",
  "\u2B50 Gold filled bar (hit)": "\u2B50 Gold-Ausgefüllter Balken (Treffer)",
  "\u{1F0CF} Magic Decks TCG": "\u{1F0CF} Magic Decks TCG",
  "\u{1F3B2} Find Opponent": "\u{1F3B2} Gegner finden",
  "\u{1F3B2} Looking for Trouble": "\u{1F3B2} Ärger suchen",
  "\u{1F3B5} Filled bar (hit)": "\u{1F3B5} Ausgefüllter Balken (Treffer)",
  "\u{1F3B5} Match": "\u{1F3B5} Match",
  "\u{1F3C6} Top 10": "\u{1F3C6} Top 10",
  "\u{1F3E0} Session Ranking": "\u{1F3E0} Sitzungs-Rangliste",
  "\u{1F3F7}\uFE0F Classify": "\u{1F3F7}\uFE0F Klassifizieren",
  "\u{1F4B0}": "\u{1F4B0}",
  "\u{1F4BE} Save Deck": "\u{1F4BE} Deck speichern",
  "\u{1F4CA} Analyze": "\u{1F4CA} Analysieren",
  "\u{1F504} Different opponent": "\u{1F504} Anderer Gegner",
  "\u{1F524} Font": "\u{1F524} Schriftart",
  "\u{1F527} Deck Builder": "\u{1F527} Deck-Baukasten",
  // Garbled emoji strings (encoding artifacts)
  "\u00E2\u00C2\u008F\u00A9 +5s": "\u00E2\u00C2\u008F\u00A9 +5s",
  "\u00E2\u00C2\u008F\u00AA -5s": "\u00E2\u00C2\u008F\u00AA -5s",
  "\u00E2\u00C2\u008F\u00B8 Pause": "\u00E2\u00C2\u008F\u00B8 Pause",
  "\u00F0\u0178\u00C2\u008F\u2020 Top 10": "\u00F0\u0178\u00C2\u008F\u2020 Top 10",

  // ── More features ──
  "Collages": "Collagen",
  "Dance Classification": "Tanzklassifizierung",
  "Audio Analysis": "Audioanalyse",
  "MIDI Seed Demo": "MIDI-Seed-Demo",
  "Honest Living": "Ehrliches Leben",
  "User-Agent": "User-Agent",
  "No BGG suggestions": "Keine BGG-Vorschläge",

  // ── Additional simple values ──
  "Beta": "Beta",
  "Question Answer": "Frage-Antwort",
  "Seed": "Seed",
  "Select a league...": "Liga auswählen...",
  "Select a location...": "Standort auswählen...",
  "Select a session to score": "Wähle eine Sitzung zum Bewerten",
  "Start:": "Start:",
  "Type a message...": "Nachricht eingeben...",

  // ── Misc remaining ──
  "Failed to choose song": "Song konnte nicht ausgewählt werden",
  "Failed to fetch audit logs.": "Audit-Protokolle konnten nicht abgerufen werden.",
  "Failed to fetch honeytokens": "Honeytokens konnten nicht abgerufen werden",
  "Failed to load analytics data": "Analyse-Daten konnten nicht geladen werden",
  "Failed to load song data.": "Song-Daten konnten nicht geladen werden.",
  "Failed to load song.": "Song konnte nicht geladen werden.",
  "Reset filters": "Filter zurücksetzen",
  "Reset to defaults": "Auf Standard zurücksetzen",
  "Template name": "Vorlagenname",
  "Templates": "Vorlagen",
  "Accepted JSON for sequence.": "JSON für Sequenz akzeptiert.",
  "Accepted: JPEG/PNG.": "Akzeptiert: JPEG/PNG.",
  "Accepted: MP4.": "Akzeptiert: MP4.",

  // ── Specific Pok strings ──
  "Pok\u00E9mon": "Pok\u00E9mon",

  // ── RTS / Tycoon ──
  "RTS Command": "RTS-Kommando",

  // ── View / Display ──
  "Display Settings": "Anzeigeeinstellungen",

  // ── Remaining audio/karaoke ──
  "Autocorrelation": "Autokorrelation",

  // ── Complete remaining values ──
  "View Product": "Produkt ansehen",
  "Suggest something for the group!": "Schlage der Gruppe etwas vor!",
  "Reconnect \u2014 game will resume automatically. Click to dismiss.": "Wiederverbindung \u2014 Spiel wird automatisch fortgesetzt. Klicken zum Schließen.",

  // ── Template/Invite ──
  "Invite Templates": "Einladungsvorlagen",

  // ── History / Versions ──
  "My History": "Mein Verlauf",
  "Version History": "Versionsverlauf",

  // ── Loading states ──
  "Loading BGG suggestions...": "BGG-Vorschläge werden geladen...",
  "Loading analytics...": "Analyse wird geladen...",
  "Loading user info...": "Benutzerinfo wird geladen...",

  // ── Description for features ──
  "Accepted JSON for sequence.": "JSON für Sequenz akzeptiert.",

  // ── Gamepad ──
  "Xbox Gamepad Controller": "Xbox Gamepad-Controller",

  // ── Tab / section labels ──
  "Topics": "Themen",
  "Marker": "Markierung",

  // ── Remaining missing ──
  "Accent": "Akzent",
  "Accent Primary": "Haupt-Akzent",
};

// ───────────────────────────────────────────────
// Helper functions for nested objects
// ───────────────────────────────────────────────
function getLeafPaths(obj, prefix = '') {
  const result = [];
  for (const [k, v] of Object.entries(obj)) {
    const p = prefix ? `${prefix}.${k}` : k;
    if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
      result.push(...getLeafPaths(v, p));
    } else {
      result.push({ path: p, value: v });
    }
  }
  return result;
}

function getNestedValue(obj, pathParts) {
  let current = obj;
  for (const part of pathParts) {
    if (current == null || typeof current !== 'object') return undefined;
    current = current[part];
  }
  return current;
}

function setNestedValue(obj, pathParts, value) {
  let current = obj;
  for (let i = 0; i < pathParts.length - 1; i++) {
    const part = pathParts[i];
    if (!(part in current) || typeof current[part] !== 'object') {
      current[part] = {};
    }
    current = current[part];
  }
  current[pathParts[pathParts.length - 1]] = value;
}

// ───────────────────────────────────────────────
// Main logic
// ───────────────────────────────────────────────
function main() {
  console.log('Reading locale files...');
  const en = JSON.parse(fs.readFileSync(EN_PATH, 'utf8'));
  const de = JSON.parse(fs.readFileSync(DE_PATH, 'utf8'));

  const enLeaves = getLeafPaths(en);
  const deLeaves = getLeafPaths(de);
  const deMap = new Map(deLeaves.map(l => [l.path, l.value]));

  // Find untranslated leaves (de value === en value)
  const untranslated = [];
  for (const leaf of enLeaves) {
    const deVal = deMap.get(leaf.path);
    if (deVal === leaf.value && typeof leaf.value === 'string') {
      untranslated.push(leaf);
    }
  }

  console.log(`Found ${untranslated.length} untranslated leaves.`);
  const uniqueVals = new Set(untranslated.map(u => u.value));
  console.log(`Unique untranslated values: ${uniqueVals.size}`);

  // Apply translations
  let translated = 0;
  let unchanged = 0;
  let missing = 0;
  const missingValues = new Set();

  for (const leaf of untranslated) {
    const parts = leaf.path.split('.');
    const enVal = leaf.value;

    if (dictionary.hasOwnProperty(enVal)) {
      const deVal = dictionary[enVal];
      setNestedValue(de, parts, deVal);
      if (deVal !== enVal) {
        translated++;
      } else {
        unchanged++; // Same in both languages (technical terms, game names, etc.)
      }
    } else {
      missing++;
      missingValues.add(enVal);
    }
  }

  // Write de.json back
  const output = JSON.stringify(de, null, 2) + '\n';
  fs.writeFileSync(DE_PATH, output, 'utf8');

  console.log('\n=== Translation Results ===');
  console.log(`Total untranslated leaves: ${untranslated.length}`);
  console.log(`Translated to German:      ${translated}`);
  console.log(`Unchanged (same in DE):    ${unchanged}`);
  console.log(`Missing from dictionary:   ${missing}`);

  if (missingValues.size > 0) {
    console.log(`\nMissing values (${missingValues.size}):`);
    const sorted = [...missingValues].sort();
    sorted.forEach(v => console.log(`  ${JSON.stringify(v)}`));
    // Write missing values to file for reference
    fs.writeFileSync(
      path.resolve(__dirname, 'missing-translations.json'),
      JSON.stringify(sorted, null, 2) + '\n',
      'utf8'
    );
    console.log('\nMissing values written to scripts/missing-translations.json');
  }

  console.log('\nDone! de.json has been updated.');
}

main();
