// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiceToDev.FunZone.Infrastructure.Database;

#nullable disable

namespace NiceToDev.FunZone.API.Migrations
{
    [DbContext(typeof(KaraokeDbContext))]
    [Migration("20250202235310_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KaraokePartyKaraokePlayer", b =>
                {
                    b.Property<int>("PartiesId")
                        .HasColumnType("int");

                    b.Property<int>("PlayersId")
                        .HasColumnType("int");

                    b.HasKey("PartiesId", "PlayersId");

                    b.HasIndex("PlayersId");

                    b.ToTable("KaraokePartyKaraokePlayer");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("KaraokeParties");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePartyPlayer", b =>
                {
                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("PartyId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("KaraokePartyPlayer");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePartyPlaylist", b =>
                {
                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.HasKey("PartyId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("KaraokePartyPlaylist");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePartyRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("KaraokePartyRound");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KaraokePlayers");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KaraokePartyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KaraokePartyId");

                    b.ToTable("KaraokePlaylists");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePlaylistSong", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("KaraokePlaylistSong");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeSinging", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<int>("Combo")
                        .HasColumnType("int");

                    b.Property<int>("Good")
                        .HasColumnType("int");

                    b.Property<int>("Hits")
                        .HasColumnType("int");

                    b.Property<int>("Misses")
                        .HasColumnType("int");

                    b.Property<int>("Perfect")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "RoundId");

                    b.HasIndex("RoundId");

                    b.ToTable("KaraokeSinging");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeSingingRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SingingId")
                        .HasColumnType("int");

                    b.Property<int>("SingingPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SingingRoundId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SingingPlayerId", "SingingRoundId");

                    b.ToTable("KaraokeRecordings");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeSongFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SongType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KaraokeSongs");

                    b.HasDiscriminator<string>("SongType").HasValue("KaraokeSongFile");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.UltrastarNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NoteLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("UltrastarNote");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.UltrastarSongFile", b =>
                {
                    b.HasBaseType("NiceToDev.FunZone.Domain.Entities.KaraokeSongFile");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Ultrastar");
                });

            modelBuilder.Entity("KaraokePartyKaraokePlayer", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokeParty", null)
                        .WithMany()
                        .HasForeignKey("PartiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeParty", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePlayer", "Organizer")
                        .WithMany("OrganizedParties")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePartyPlayer", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokeParty", "Party")
                        .WithMany("PartyPlayers")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePartyPlaylist", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokeParty", "Party")
                        .WithMany("PartyPlaylists")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePlaylist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePartyRound", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokeParty", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePlayer", "Player")
                        .WithMany("Rounds")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePlaylist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokeSongFile", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("Player");

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePlaylist", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokeParty", null)
                        .WithMany("Playlists")
                        .HasForeignKey("KaraokePartyId");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePlaylistSong", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePlaylist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokeSongFile", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeSinging", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePlayer", "Player")
                        .WithMany("Singing")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokePartyRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeSingingRecording", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.KaraokeSinging", "Singing")
                        .WithMany("Recordings")
                        .HasForeignKey("SingingPlayerId", "SingingRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Singing");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.UltrastarNote", b =>
                {
                    b.HasOne("NiceToDev.FunZone.Domain.Entities.UltrastarSongFile", "Song")
                        .WithMany("Notes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeParty", b =>
                {
                    b.Navigation("PartyPlayers");

                    b.Navigation("PartyPlaylists");

                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePlayer", b =>
                {
                    b.Navigation("OrganizedParties");

                    b.Navigation("Rounds");

                    b.Navigation("Singing");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokePlaylist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.KaraokeSinging", b =>
                {
                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("NiceToDev.FunZone.Domain.Entities.UltrastarSongFile", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
