using System.Text;

namespace AudioVerse.SetupWizard;

public static class NginxTemplate
{
    public static string Generate(string serverName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("user  nginx;");
        sb.AppendLine("worker_processes  auto;");
        sb.AppendLine("error_log  /var/log/nginx/error.log warn;");
        sb.AppendLine("pid        /var/run/nginx.pid;");
        sb.AppendLine();
        sb.AppendLine("events {");
        sb.AppendLine("    worker_connections  1024;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("http {");
        sb.AppendLine("    include       /etc/nginx/mime.types;");
        sb.AppendLine("    default_type  application/octet-stream;");
        sb.AppendLine("    sendfile        on;");
        sb.AppendLine("    keepalive_timeout  65;");
        sb.AppendLine();
        sb.AppendLine("    upstream audioverse_api {");
        sb.AppendLine("        server api:5000;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    upstream audioverse_identity {");
        sb.AppendLine("        server identity:5002;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    upstream audioverse_react {");
        sb.AppendLine("        server react:80;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    # Block scanners / bots without valid Host");
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 80 default_server;");
        sb.AppendLine("        listen 443 ssl default_server;");
        sb.AppendLine("        ssl_certificate /etc/nginx/certs/fullchain.pem;");
        sb.AppendLine("        ssl_certificate_key /etc/nginx/certs/privkey.pem;");
        sb.AppendLine("        return 444;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 80;");
        sb.AppendLine($"        server_name {serverName};");
        sb.AppendLine("        location /.well-known/acme-challenge/ {");
        sb.AppendLine("            root /var/www/certbot;");
        sb.AppendLine("        }");
        sb.AppendLine("        return 301 https://$host$request_uri;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 443 ssl;");
        sb.AppendLine("        http2 on;");
        sb.AppendLine($"        server_name {serverName};");
        sb.AppendLine();
        sb.AppendLine("        ssl_certificate /etc/nginx/certs/fullchain.pem;");
        sb.AppendLine("        ssl_certificate_key /etc/nginx/certs/privkey.pem;");
        sb.AppendLine();
        sb.AppendLine("        # API — /api/* and /swagger/*");
        sb.AppendLine("        location /api/ {");
        sb.AppendLine("            proxy_pass http://audioverse_api;");
        sb.AppendLine("            proxy_http_version 1.1;");
        sb.AppendLine("            proxy_set_header Upgrade $http_upgrade;");
        sb.AppendLine("            proxy_set_header Connection \"upgrade\";");
        sb.AppendLine("            proxy_set_header Host $host;");
        sb.AppendLine("            proxy_cache_bypass $http_upgrade;");
        sb.AppendLine("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
        sb.AppendLine("            proxy_set_header X-Forwarded-Proto $scheme;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        location /swagger {");
        sb.AppendLine("            proxy_pass http://audioverse_api;");
        sb.AppendLine("            proxy_set_header Host $host;");
        sb.AppendLine("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
        sb.AppendLine("            proxy_set_header X-Forwarded-Proto $scheme;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        # SignalR hubs");
        sb.AppendLine("        location /hubs/ {");
        sb.AppendLine("            proxy_pass http://audioverse_api;");
        sb.AppendLine("            proxy_http_version 1.1;");
        sb.AppendLine("            proxy_set_header Upgrade $http_upgrade;");
        sb.AppendLine("            proxy_set_header Connection \"upgrade\";");
        sb.AppendLine("            proxy_set_header Host $host;");
        sb.AppendLine("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
        sb.AppendLine("            proxy_set_header X-Forwarded-Proto $scheme;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        # Identity Server — /connect/*");
        sb.AppendLine("        location /connect/ {");
        sb.AppendLine("            proxy_pass http://audioverse_identity;");
        sb.AppendLine("            proxy_set_header Host $host;");
        sb.AppendLine("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
        sb.AppendLine("            proxy_set_header X-Forwarded-Proto $scheme;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        # Health check endpoint (for Docker / load balancers)");
        sb.AppendLine("        location = /nginx-health {");
        sb.AppendLine("            access_log off;");
        sb.AppendLine("            return 200 'ok';");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        # React SPA — everything else");
        sb.AppendLine("        location / {");
        sb.AppendLine("            proxy_pass http://audioverse_react;");
        sb.AppendLine("            proxy_set_header Host $host;");
        sb.AppendLine("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
        sb.AppendLine("            proxy_set_header X-Forwarded-Proto $scheme;");
        sb.AppendLine("            proxy_intercept_errors on;");
        sb.AppendLine("            error_page 404 = /index.html;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
